odoo/owl

- doc/component.md
- doc/hooks.md
- src/component/component.ts
- src/hooks.ts
- tests/component/component.test.ts
- tests/hooks.test.ts
This commit also changes the behaviour of willPatch and patched: they no
longer transfer data from one to the other, because it can be done
cleanly by hooks and a closure.
closes #307
> [IMP] hooks: add onWillPatch and onPatched

- tools/playground/samples.js
Sadly, Firefox does not support yet static class fields, so we need to
use an equivalent, but slightly not as nice, syntax.
closes #335
> [FIX] playground: update samples to make them work on firefox

- src/component/directive.ts
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/props_validation.test.ts
it is not useful to do it in the component directive, especially since
it is done in the constructor, and the default props are not applied.
closes #379
> [FIX] component: do not validate props twice

- doc/reference/component.md
- src/component/component.ts
- tests/component/component.test.ts
Re-render the component all the time before remounting it, which
seems safer anyway.
In the test, we had to add a nextTick to wait for the changes to
be notified (before, we waited thanks to the additional call to
mount). If we don't do the nextTick, mount is called, and render
is called right after (before the promise returned by mount is
resolved). This scenario doesn't work right now (see #441).
Closes #381
> [REF] component: mount: remove renderBeforeRemount option

- src/component/component.ts
- src/component/fiber.ts
- tests/component/component.test.ts
Whenever a rendering is completed, we need to reset the currentFiber
to null to make sure all subsequent renderings will not be
confused.
However, the way it was done before this commit was wrong in a
specific situation: we resetted the currentFiber to null in the
patch method.  The idea was that this method was called every time
the component completes a rendering. But this is not true: it
can happen that a component is unmounted and remounted without
changes.  Then the component will be patched, but if there is no
change, it will not call recursively the patched methods of its
children.
So, we need to choose a better place to reset it to null.
closes #454
> [FIX] component: properly set currentFiber to null in all cases

- tools/playground/app.js
The generated downloaded code from the playground did not work because
it did not load templates into QWeb anymore.
closes #461
> [FIX] playground: fix downloaded app code

- package.json
- src/vdom/html_to_vdom.ts
Before this commit, a condition deemed always true made
the building crash. The happened with TypeScript == 3.7.2
After this commit, the required typescript version has been
changed, as well as the incriminated true condition
> [FIX] package, vdom: condition always true, TS 3.7.2

- src/component/component.ts
- src/component/fiber.ts
- src/component/scheduler.ts
- src/qweb/expression_parser.ts
- tests/component/component.test.ts
- tests/qweb/qweb_expressions.test.ts
Errors from mounted/willPatch/patched should be returned to caller
(either mount or render functions)
part of #410
> [FIX] component: propagate errors to caller

- src/component/component.ts
- src/component/directive.ts
- src/component/fiber.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/context.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
Following 2922cee6ea9b9f
Previous commit was not correct: used children with a cancelled
fiber (for instance, with a new currentFiber) could be destroyed.
This commit fixes the issue differently, by directly detecting
children that are not used anymore (and not mounted), and destroy
them directly (no need to wait for willStart promise to be resolved
anymore).
> [FIX] component: destroy not yet mounted components (2)

- src/component/component.ts
- tests/component/component.test.ts
It could happen that a component would crash. But then, the __render
code tried to copy the class properties into the vnode, which does not
exist, creating a new error.
So, the solution is to process the classObj only in the succesful part
of the render call, which then will not crash, so the normal error
handling will occur.
> [FIX] component: display correct error in some case

- tests/context.test.ts
We learn something new every day, and today is no exception. Promise.all
of a pending promise does not actually resolve as fast as possible after
the initial promise is completed, but a small delay after, because it is
put on the macrotask queue or something like that (I assume)
closes #480
> [FIX] context tests: make them deterministic

- src/component/fiber.ts
- tests/component/component.test.ts
It is important to reset the isRendered flag to false to ensure
that other (subsequent) simultaneous calls to render will be
skipped, as the currentFiber is actually no yet (re-)rendered.
Closes #483
> [FIX] component: reset isRendered when reusing fiber

- doc/reference/component.md
- src/qweb/qweb.ts
- tests/component/component.test.ts
Before this rev, using t-component on a div (for example) node
would silently ignore the div and replace it by the root node of
the component. A way to improve this was to create an extra div
node and to put the component inside it. However, it raised
questions: what do we do with other attributes set on this tag?
Do we apply them on the div, or on the component? In addition,
some of them only make sense on the component (e.g. props), so we
have to detect them. Whatever we would have decided, it wouldn't
have been obvious from the user point of view, so we chose not to
support it, and we thus now raise an error in this case.
Closes #487.
> [IMP] qweb: throw error if t-component not used on a node t

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Have a t-call having a t-raw="0"
that call is made to a template of the same form
i.e. itself as a t-call t-raw="0" structure
Before this commit, there was recursion crash
This was because the caller to which a t-raw="0" referred to
was incorrect. The caller here is the node which makes the t-call.
In particular, the caller was always set to last caller of the context
After this commit, there is no crash and this imbrication
of t-call and t-raw="0" is well rendered.
To sum up, we count the recursive calls to t-raw="0" and fetch
the caller in the context accordingly
closes #510
> [FIX] qweb: cascading t-call and t-raw="0"

- src/qweb/qweb.ts
- src/vdom/modules.ts
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
The classList.add method actually crashes when given an empty string (or
a string with just white spaces).
closes #530
> [FIX] qweb: properly handle empty class attribute

- src/misc/portal.ts
- tests/misc/portal.test.ts
Before this commit, when manually unmounting the portal
or one of its parents, the teleported elements were not cleaned
and stayed teleported forever
After this commit, the teleported content is brought back and
unmounted much like any component
closes #531
> [FIX] portal: manually unmounting works

- src/component/directive.ts
- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/helpers.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/router/__snapshots__/link.test.ts.snap
Unmounted components should be considered inactive, at least from the
perspective of Owl itself.
closes #543
> [FIX] qweb/component: do not call handlers for unmounted components

- doc/reference/component.md
- src/component/component.ts
- src/component/fiber.ts
- tests/component/component.test.ts
A component can now be mounted in different positions: either 'before' (at
the start), 'after' (at the end), or 'attach' (take possession of a target
element)
closes #539
> [IMP] component: add position option to mount method

- src/qweb/base_directives.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
When a t-call has a condition and a body
the t-if's and its flavors should be ignored when compiling the body of a t-call
> [FIX] qweb: conditional t-call with body

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- src/qweb/qweb.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/router/__snapshots__/link.test.ts.snap
- tests/router/__snapshots__/route_component.test.ts.snap
While it is not tested, nor documented, the reference QWeb
implementation display the `false` value as "false". So, we have to
adapt the Owl implementation to match that behaviour.
At the same time, this commit uses 'let' instead of 'var' in various places,
to make the compiled code more consistant.
> [FIX] qweb: properly display falsy values

- src/qweb/base_directives.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
Before this commit, when template was t-call'ed and defined
t-component directive within it, there was a crash because extra.parent was never defined
After this commit, this use case works
> [FIX] qweb: t-call must pass extra parent

- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
Since t-call is now a function call, we need to properly handle the
internal key used to find previous components.  If a t-call is inside a
t-foreach, then we need to transfer the key to the sub template.
Otherwise, each component in the subtemplate will be associated to the
same key, which means that it will lead to big issues: components are
destroyed and reused...
closes #581
> [FIX] qweb: t-call properly transfer key to sub components

- src/store.ts
- tests/store_hooks.test.ts
Because `typeof null === 'object'`.
> [FIX] store: prevent crash when selector returns `null`

- src/component/directive.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
The expression parser properly format an empty string into an empty
string. But then, this empty string was injected in the props object of
a component, and the compiled code looked like this:
let props5 = { val: };
So, in this case, we simply put undefined, since there are no props
value.
closes #587
> [FIX] component: no crash if empty props

- src/component/styles.ts
- tests/component/styles.test.ts
This PR fixes the css selector generation for nested rules
Before this fix, a selector like:
```css
.parent {
.child-a, .child-b {
color: red;
}
}
```
was generated as:
```css
.parent .child-a, .child-b {
color: red;
}
```
Now it generates:
```css
.parent .child-a, .parent .child-b {
color: red;
}
```
#592
> [FIX] styles: fix rule selector generation

- src/qweb/base_directives.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tools/playground/samples.js
Before this commit, owl could crash in some specific situations:
multiple t-calls with sub components, outside a loop.  The reason is
that the t-call did not generate a key, so from the point of view of the
children component, it had the same key, even though it was at a
different place in a template.
Also, with this fix, we can fix the playground responsive example.
closes #602
> [FIX] component: multiple t-calls

- doc/reference/tags.md
- src/component/styles.ts
- tests/component/styles.test.ts
This PR adds the support of the & selector.
This selector is useful to join a subrule with a parent selector.
example:
```scss
button {
&:hover {
background-color: red;
}
}
```
will give
```css
button:hover {
background-color: red;
}
```
part of https://github.com/odoo/owl/issues/591
> Handle & selector

- src/component/component.ts
- tests/component/async.test.ts
Asynchronous rendering is subtle. Before this commit, it was possible
(though not easy) to get into a situation where the Owl rendering
pipeline decremented twice the counter of a fiber that indicates that
its work is complete.
The situation occurs in the `render` method, where we create a fiber,
wait for a micro tick before starting the actual rendering (the goal was
to batch all changes coming from a single call stack). However, in this
microtask tick, it was possible that the fiber was cancelled, and we did
not have a check for that.
> [FIX] component: resolve a subtle concurrency issue

- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: ignore comment nodes between t-if/t-elif/t-else

- src/component/directive.ts
- tests/component/__snapshots__/class_style.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
Before this commit, creating a sub component with
t-att-style/t-att-class attributes or with t-on- event handlers would
override the *hook* object rendered by the sub component.
This is an issue for some directives, such as t-ref, which defines
hook functions.
This commit fixes the issue by checking for an override, and wrapping
the hooks in a function that calls each defined hook.
closes #638
> [FIX] component: merge hooks properly

- src/qweb/extensions.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/animations.test.ts
This commit should fix crashes coming from transition code on nodes.
This does not impact transitions on components.
closes #637
closes #641
> [FIX] transition: no crash if added/removed quickly

- src/component/fiber.ts
- tests/component/un_mounting.test.ts
Have
```xml
<body t-name="webclient" />
```
and
```js
const comp = new WebClient();
comp.mount(document.body, {position: 'self'});
```
Before this commit, the body that was there before anything had happened
was *replaced* by the new body node created by the WebClient OWL component
After this commit, we ensure that the element body is the same at reference level
> [FIX] component: self mounting position keeps the reference

- src/qweb/compilation_context.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Have something like
```xml
<div t-name="Parent">
<t t-call="nodeTemplate">
<t t-set="recursive_idx" t-value="1"/>
<t t-set="node" t-value="root"/>
</t>
</div>
<div t-name="nodeTemplate">
<t t-set="recursive_idx" t-value="recursive_idx + 1"/>
<p><t t-esc="node.val"/> <t t-esc="recursive_idx"/></p>
<t t-foreach="node.children or []" t-as="subtree">
<t t-call="nodeTemplate">
<t t-set="node" t-value="subtree"/>
</t>
</t>
</div>
```
Where we want to propagate a recursion index through recursive t-calls
Before this commit, it did not work as we protected the scope in order
to not leak, in the wronf manner. Namely the protected scope only took
firt level prototype properties of the original scope.
After this commit, this case works as we mark the scope as read only
solves #672
> [FIX] qweb: protect scope in t-call writing recursively

- src/hooks.ts
- tests/hooks.test.ts
If the brackets are not corrected, the 'onWillStart' and 'onWillUpdateProps' don't work if given with async functions.
> [FIX] hooks: order of brackets for multiple async hooks

- src/component/component.ts
- tests/component/component.test.ts
It is possible that a Component is extended dynamically and if this is
the case, the class that extends it can be anonymous, with property
name=''. If this is the case, current implementation interprets the empty
string to be false so the while loop is terminated without further
scanning the super classes.
In this proposal, we allow anonymous class to be scanned until its
Component ancestor. Basically, the anonymous class assumes the name of
it super.
> [IMP] allow anonymous Component extensions

- src/hooks.ts
- tests/hooks.test.ts
With this commit, we can get the type for the target component for a
ref.
By default, if the generic type is not given, the ref will simply use
the base Component type.
> [IMP] hooks: improve useRef typings

- src/qweb/base_directives.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Before this commit, the generated code was incorrect, and crashed,
when there was a t-esc="abc" in a subtemplate, with t-set="abc"
done outside the subtemplate, with syntax <t t-set="abc">value</t>.
> [FIX] qweb: t-esc inside t-call using outside t-set

- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
With QWeb, we can register globally templates (using the xml tag or
the registerTemplate function). However, these templates, once
compiled, can generate sub template compiled functions. Before this
commit, these sub functions were local to a specific instance.
This means that creating a new QWeb instance and rendering a global
parent template would crash, since it was unable to find the actual sub
function.
This commit fixes the issue: the sub functions are now shared
statically, but with a unique ID, so we do not have issues with sub
functions having a same name in different QWeb instance.
closes #701
> [FIX] qweb: properly handle subtemplates in shared templates

- src/vdom/html_to_vdom.ts
- tests/vdom.test.ts
Before this commit, t-raw a string containing `<svg>` did not display
the svg element. This was because of missing namespace in vnode's data.
Now, `vdom.addNS` is called to add the svg namespace when necessary.
> [FIX] qweb: support of svg in t-raw

- src/qweb/base_directives.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Have a t-call nested in a t-foreach nested in a t-foreach
```xml
<t t-name="template">
<t t-foreach="..." t-as="a">
<t t-foreach="..." t-as="b">
<t-call="templateCalled" />
</t>
</t>
</t>
```
Before this commit, the `a` variable was not accessible within the t-call.
That was because the way t-call protected its scope by hiding other protected scope
in this case, the first protected scope for the first `t-foreach` was hidden
After this commit, `a` and `b` are accessible in the t-call, whether the t-call
defines its own variables by `t-set` or not.
Also, as expected from other fixes, there is no leaks of variables defined within a `t-call`
fixes #695
> [FIX] qweb: t-call should protect scope and let it accessible

- doc/reference/props_validation.md
The validation type should be a String object.
> [DOC] props validation: The validation type should be a String object.

- src/component/fiber.ts
- tests/component/component.test.ts
Have a hierarchy of A, B, C components where:
```xml
<div t-name="A">
<div>
<B t-key="key1"/>
</div>
</div>
<t t-name="B">
<C t-key="key2"/>
</t>
<div t-name="C">
<div><t t-esc="keys_as_props" /></div>
</div>
```
The subtility of the issues lies in B, which doesn't have its own
concrete DOM element, rather, it borrows it from C.
With the sequence of events:
- change key2
C1 is destroyed and replaced by another instance, and another node.
B1 has its props updated and is patched with the C2's node (CRITICAL)
A1 is patched
- change key1 AND key2
C2 is destroyed
B1 is destroyed
A1 is patched replacing B1 by B2, and their nodes too (which at this point should be C2's to C3's)
Before this commit, at the CRITICAL point, the node representing the component itself
(technically its pvnode) was not …
> [FIX] component, fiber: update props with virtual node should not crash

- src/component/component.ts
- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/component.test.ts
- tests/component/un_mounting.test.ts
- tests/vdom.test.ts
Owl has to manage a lot of interesting situations.  One of them is when
a rendering is initiated, which creates a sub component, but then
another rendering starts, which invalidate the previous one, and will
create another sub component.  Since the first sub component was not
ever in the DOM, we cannot rely on the vdom patching process to remove
it, so we have to do it manually.
Sadly, this is actually a very tricky situation, since there are other
subtle situations where the code that remove an unmounted widget could
be executed, in particular when the parent component is unmounted, then
remounted, then modified to trigger yet another rendering.
In this commit, we handle this case more carefully by making sure that
the destroyed subcomponent properly configures its pvnode so the patch …
> [FIX] component: subtle issue with unmounted children

- src/component/component.ts
- src/component/fiber.ts
- tests/component/component.test.ts
Here is a situation that can happen in some complicated case:
1. a parent component is rendered, which includes some children
2. it is then willPatched
3. the sub components are then mounted/willUnmounted
4. because of complicated business logic, this causes the parent
component to be rerendered (before parent "patched" method is called)
5. owl will internally reset its currentfiber to null (but there is a
pending rendering!)
6. subsequent rendering will ignore pending rendering
7. havoc ensues
This is actually one of the reason why modifying a component state in a
willPatch component is actually not a good idea.  However, the good news
is that this specific situation can be properly handled: we can simply
make sure that we do not reset currentFiber to null if there is a new
pending …
> [FIX] component: make concurrent renderings more robust

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
The body of a t-call directive may be used to define private variables
to the sub template call.
However, the code that handle t-call worked like this:
- compile sub template if necessary
- then compile body of t-call to extract variables
This means that the variables defined in the t-call body were not yet
processed and available in the context.  Because of that, when the call
to t-esc is done, there is not internal qweb var, and the code simply
outputs a scope['varname'], which is in our case a VDOMArray, so it is
displayed as [object object]
> [FIX] qweb: fix issue variables set in body of t-call

- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/qweb/qweb.test.ts
Sometimes, HTML is slightly more subtle than what I initially expect.
Rendering some html is simple, we have tags and attributes.  However,
once we add behaviour, then the situation is more complex:
<input value="abc"/>
is an input with an INITIAL value of "abc", but the attribute does not
actually represent the CURRENT value of the input, which may be
different if the user did change it.
This is basically the difference between "attribute" and "property".
So, when rendering html with owl, we sometimes want to actually set
the property (current value), instead of the html attribute.
This commit make sure that this is the case for inputs with the "value"
attribute.
closes #722
> [FIX] qweb: handle input value attribute as a property

- src/component/props_validation.ts
- tests/component/props_validation.test.ts
Because of a "break" statement instead of "continue", the check for valid
props was stopping as soon as it met an optional props, which kind of
invalidate the whole system.
closes #717
> [FIX] component: properly validate multiple props

- tests/helpers.ts
Before this commit, we artificially replaced in the tests the
requestAnimationFrame by a setTimeout, to actually increase the speed of
the tests.  However, this is not really a true replacement.  For
example, a real setTimeout can come before or after a real
nextAnimationFrame, depending on when/where it is requested.
Also, this change exposed another problem: the nextTick function did a
setTimeout before a nextanimationframe. This is not a problem when
nextAnimationFrame is replaced by a setTimeout, because then all
expectations holds in owl.  However, it is wrong: to get to the next
animation frame, we need to request an animation frame, and THEN wait
with a setTimeout.
closes #729
> [FIX] test: timing issue

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
Before this commit, a variable set in a template with t-set could be
passed to a subcomponent as a prop only if it was only textual. If the
value was defined in the body of the t-set directive, it was passed, but
as a VDomArray, which means that it will only be displayed as [object
object] or something.
Also, we do not want to leak the VDomArray abstraction in userland (code
written by people using owl).
This issue is actually quite a problem in practice, because values in a
templates are translated, but not in attributes.  Therefore, using a
t-set directive with a body text content is the proper way to have
translated values at runtime.
closes #670
> [FIX] component: allow var with body as (textual) props

- src/core/observer.ts
- src/qweb/qweb.ts
- tests/core/observer.test.ts
Promises are kind of special, and do not behave like usual javascript
values.
For this issue, the problem is that when the observer tries to observe a
promise value, the code will crash with an error like this:
Uncaught TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
Also, note that it does not make much sense to proxify promise methods
anyway, since they are not (supposed) to be modified.
So, with this commit, we simply consider that promises should be treated
like a primitive value: simply ignored when determining if it should be
proxified
Note that I actually believe that putting promises in a useState is not
a good idea in general.
closes #677
> [FIX] observer: does not proxify promises

- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/slots.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
This is a rarely (if ever) used feature, but according to our qweb
reference implementation, it is possible to use the
t-call directive on an arbitrary html tag, like this:
<div t-call="my.template"/>
It is then interpreted as:
<div><t t-call="my.template"/></div>
So, with this commit, we make sure that the owl qweb implementation
matches that behaviour.
closes #706
> [FIX] qweb: allow t-call on arbitrary html nodes

- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Input with type="checkbox" have a special property (indeterminate) to
visually display the fact that the input value is non determinate (in my
chrome browser, the checkbox is then drawn with a simple - inside). It
does not actually modify the value of the input, only the way it is
displayed.
So, with this commit, owl will properly set the property, as expected.
closes #713
> [IMP] qweb: add indeterminate to special input properties

- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
Before this commit, the t-model directive worked well with expressions
such as "state.value", but not with bracketed expression: "state[value]"
(it generated invalid code).
This commit make the t-model smarter by detecting this case, and
properly capturing the base expression and key variable.
closes #694
> [FIX] t-model: support expressions with [ ]

- src/component/directive.ts
- tests/component/slots.test.ts
Previous code naively handled nested t-set-slots: if a second named
slots was found, it overrode the first.
In this commit, we use a set to make sure that we only use the first
found t-set-slot node.
Note that it works as expected because document.querySelectorAll
performs a search depth first, so we will always use the named slots
closer to the parent element, in term of depth.
closes #682
> [FIX] slots: properly handle named t-slots inside named t-slots

- .gitignore
- package.json
- rollup.config.js
- tools/server.py
- tsconfig.json
The bundle pipeline can use a bit of a improvement:
Most of the process is moved from npm scripts to rollup.
Add package keys to smooth out the use of bundlers of the end users.
(Rollup by example check amongst others the main, module and browser key
to import the right version of a lib when needed).
Refactor rollup logic to make it more modular.
Add bundled module formats.
> [IMP] bundling: Improve owl bundling process and output

- src/vdom/html_to_vdom.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
The code converting html to a vnode did not handle comment nodes as
expected.
closes #761
> [FIX] qweb: do not render comments as text in t-raw

- doc/reference/qweb_templating_language.md
- src/component/directive.ts
- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/router/__snapshots__/link.test.ts.snap
Strangely, the _compile method required a CompilationContext whenever it
was compiled as a sub template, but this parent context was actually not
really needed.  I guess that it was the case in the past, but this was
changed at some point.
> [REF] qweb: simplify _compile method arguments

- src/qweb/base_directives.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
Whenever a top level t-call was made with some non empty body, Owl
complained that a template should not have more than one root node.
The reason was that the compilation context for the body of the t-call
directive was the same as the root compilation context, and it already
had a parentNode set.
To fix the issue, this commit simply use the subContext method to create
a different compilation context, which actually makes sense, because the
body of a t-call is really a different situation.  Also, as a bonus, it
slightly improves the code for the t-call directive.
closes #760
> [FIX] qweb: correctly handle top level t-call and body

- doc/reference/qweb_templating_language.md
Owl is meant to stay low level-ish, and making it work magically with
sets/maps/... seems to be a little too much in term of code/magic. Also,
using iterables in t-foreach is actually quite simple, making this
improvement not as important.
closes #720
closes #754
> [DOC] qweb: explain how to work with iterables in t-foreach

- tests/animations.test.ts
- tests/helpers.ts
Since commit 7e4baf6, some tests were failing non deterministically. It
seems like the root cause for the problem is that the nextTick method
was sometimes completed too early.
From my understanding of the problem, the nextTick method was correct,
however it is running in a jest test, in node, which simulates the
requestanimationframe behaviour, probably not perfectly.
Switching to an alternate implementation, which swaps the setTimeout and
the requestanimationframe seems to be more solid.
Note that this commit had to introduce the nextFrame method as well,
because the animation tests really seems to want to be in the next
frame, not in a callback executed in the same frame, but at the end.
closes #757
> [FIX] tests: fix cause of non determinism

- src/qweb/base_directives.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
The previous implementation generated an id each time the template was
rendered, instead of just once per new dynamic template found.
> [FIX] qweb: issue when rendering twice dynamic t-calls

- doc/reference/config.md
- src/config.ts
- src/qweb/extensions.ts
- src/qweb/qweb.ts
It is useful to be able to disable the t-transition directive for
testing purposes.  This commit introduces a global config flag to do
just that.
closes #768
> [IMP] config: add enableTransitions flag to config

- doc/reference/event_handling.md
- src/component/component.ts
Just to have nice and beautiful type hinting like that:
> [IMP] component: allow using TypeScript type hints

- doc/reference/event_handling.md
- src/component/component.ts
- src/component/directive.ts
Fun: the transition is handled at two different places, once for dom
nodes, once for components.  Obviously, I only applied the change to the
first case and forgot about the second.
> [FIX] config: make enableTransitions work on components

- src/component/directive.ts
- tests/component/slots.test.ts
- tools/release.js
The reviewer for the commit on named slots inside named slots did not
notice that there was an infinite loop.  Because of his sloppiness, Owl
could block in an infinite loop when a named t-slots was defined inside
a subcomponent, but not as a direct child.
> [FIX] slots: prevent infinite loop in some cases

- doc/reference/animations.md
The documentation was a bit missleading around which and when css
classes were added to the DOM.
Also added a scss mixin usage exemple.
> [DOC] Fix animation documentation

- doc/readme.md
- doc/reference/animations.md
- doc/reference/browser.md
- doc/reference/content.md
- doc/reference/environment.md
- src/browser.ts
- src/component/component.ts
- src/index.ts
This commit performs two tasks:
1. it exports the internal browser object (in owl.browser), for ease of
testing
2. it makes sure that Owl does not crash inside iframes in incognito
mode, because window.localStorage raises an exception in that case
closes #791
> [FIX/IMP] export browser object, prevent crash in private mode

- src/component/component.ts
- tests/component/un_mounting.test.ts
Components can implement shouldUpdate to return false.  In that case,
renderings coming from above should be ignored.
However, if the component was unmounted and is remounted, we actually
need to force a rerendering in that case, so it is mounted, otherwise
the subcomponent is left in unmounted state, which means that rendering
are ignored.
closes #800
> [FIX] component: force mounting subcomponents with shouldUpdate

- src/context.ts
- src/store.ts
- tests/context.test.ts
- tests/store_hooks.test.ts
Before this commit, an unwanted behaviour happened when using components
with shouldUpdate implemented, and store/state.
The actual problem is the following: the sub component is using a store,
and shouldupdate.  Whenever the component is rendered, it checks if there is an incoming
rendering from the context.  If that is the case, it skips the
rendering, because we actually only want to be rendered by the store
rendering (otherwise, we may run into issue with inconsistent data (more
recent data from the context, older data in the component).
However, if shouldUpdate is implemented, then the rendering coming from
the context simply does not arrive.  To fix this, we just force these
renderings to go through all children, regardless of their shouldUpdate
status.
closes #799
> [FIX] store: properly render, even if shouldupdate is implemented

- doc/reference/component.md
- src/component/fiber.ts
- tests/component/async.test.ts
In some cases, a rendering initiated in some component is then remapped
into a larger rendering initiated by some parent.
If we have some components which implement shouldUpdate to return false,
then the following scenario can happen:
- some parent component is mounted (which triggers a rendering with
force: true => bypass the shouldUpdate)
- some sub component is updated and rerendered, AFTER the previous
rendering goes through it
- the sub component notices that there is an ongoing rendering, and
remaps itself in the parent rendering
Before this commit, the new fiber in the subcomponent does not have
force flag set to true, so the new rendering for the subcomponent does
not go through its own children (if they have shouldUpdate=false)
With this commit, we make sure that the flag of the …
> [FIX] component: propagate correct info when reusing fibers

- doc/learning/tutorial_todoapp.md
- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/router/__snapshots__/link.test.ts.snap
From the beginning, Owl was designed to only call event handler on
components that are mounted in the DOM.  The main benefit is that if a
component is destroyed, we are guaranteed to not execute any useless (or
potentially dangerous code).
However, there is one downside: if a component tree is being mounted,
and a child component trigger an event in its mounted hook, then it
cannot be caught by the parent, since the parent is technically not yet
mounted.
This may not be a good situation, but the point is that Owl
unnecessarily prevent the handler to be called.
We can fix this issue by simply checking if the component is not destroyed
instead of checking that it is mounted.
closes #809
> [IMP] component: can trigger event handlers even if unmounted

- package.json
- src/qweb/expression_parser.ts
- tests/qweb/qweb_expressions.test.ts
The QWeb expression parser use an object as a mapping between some
strings and the desired output in the compiled template.  However, as we
should all know, objects are not Maps, they have some additional
properties, such as "constructor" or "hasOwnProperty".
The simple solution is to make sure the mapping object does not have
anything in its prototype chain to pollute its purpose.
closes #835
> [FIX] qweb: prevent issue with builtin object properties

- src/component/component.ts
- src/component/directive.ts
- src/component/fiber.ts
- src/qweb/extensions.ts
- tests/component/__snapshots__/class_style.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/async.test.ts
- tests/component/component.test.ts
- tests/component/error_handling.test.ts
- tests/component/un_mounting.test.ts
- tests/helpers.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/router/__snapshots__/link.test.ts.snap
- tools/debug.js
With this commit, we introduce the status internal number, which
represents the current state of the component. It can currently have 4
values:
- CREATED (component is created and not rendered yet)
- RENDERED (component has been rendered at least once, and is not in the
DOM)
- MOUNTED (component has been rendered, and is in the DOM
- DESTROYED
This status number replaces the isMounted and isDestroyed boolean flags.
It has the advantage of making sure that the component is in a
consistent state (it is no longer possible to be destroyed and mounted,
for example)
Another advantage is that it gives us an easy way to track the fact that
a component has been rendered, but is not in the DOM.  This is a subtle
situation where some various events can happen, and we need to be able
to react to that …
> [REF] component: use a status number instead of flags

- src/component/directive.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/__snapshots__/class_style.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/component.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
Previously, the order of resolution was:
- components defined on the class of the current component
- components defined on the QWeb instance
- the current instance's context
This is unnatural because it doesn't go from most specific to least, as
the current instance's context is the most specific. This is also
fragile, as adding components to the QWeb instance can break unrelated
components.
This commit fixes that by making the lookup start with the current
component's context instead
> [FIX] qweb: fix order of lookup in t-component directive

- src/router/router.ts
- tests/router/route_component.test.ts
- tests/router/router.test.ts
- tests/router/test_router.ts
Before this commit, params in paths had to be be between slashes and
comprise the entirety of the contents between those slashes (eg:
`/books/{{id}}/{{name}}`)
This is unnecessarily restrictive. This commit removes this restriction,
which allows for paths such as:
- `/books/{{id}}-{{name}}`
- `#books&id={{id}}&name={{name}}`
among others
closes #858
> [FIX] router: add support for more arbitrary param placements in paths

- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/slots.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
Have a t-call within a t-set-slot of a component.
The called template has a t-component directive.
It should be like:
```xml
<t t-name="Zero">
<Slotted>
<t t-call="someTemplate" />
</Slotted>
</t>
<t t-name="someTemplate">
<SomeComponent />
</t>
```
Before this commit, the parent of SomeComponent was the Zero component
After this commit, the parent of SomeComponent is the Slotted Component as it should be
closes #862
> [FIX] qweb, t-call: t-call nested in t-slot

- src/config.ts
Backport of odoo/odoo@e4834fce692b7eb6fe6cfc66a8e5daed814c0230
There's no way to easily disable / silence this warning, because
multiple tours explicitly opt into debug mode (with good reasons). So
it's not enough to bypass the `mode` setter in the test setup helpers
and set `QWeb.dev` directly (which works for test_main in POS and
main_tests in web), there would also need to be special workarounds in
the 4 modules which set `owl.config.mode` based on the session's debug
mode.
I'm not sure how useful this warning is: it defaults to `false` so the
only situation in which this would be relevant would be for a
third-party to use Owl *and* explicitly enable the debug mode
in-source *and* forget to remove it when deploying to production *and*
look at their console.
> [CHG] config: flip debug mode warning to info

- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
Hello @ged-odoo here is a proof of concept for what I believe is a non-breaking change that would allow supporting all callable event handlers until we have arrow functions support.
This would resolve the main issue I have with not being able to access the event for now.
Let me know what do you think.
> [IMP] component: add support for callable expression in event handler

- src/component/directive.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
Before this commit, props and t-props were computed like
`Object.assign(props, t_props)`.
Now, it computes like `Object.assign(t_props, props)` so props will
override t-props.
closes https://github.com/odoo/owl/issues/886
> [IMP] directive: make props override t-props

- src/qweb/expression_parser.ts
- tests/qweb/qweb_expressions.test.ts
Before this commit, using an expression such as "{machin}" was compiled
in qweb into "{scope['machin']}" which is not valid.
With this commit, we instead transform it into "{machin:
scope['machin']}".
closes #885
> [FIX] qweb: properly parse short object description

- src/router/router.ts
- tests/router/router.test.ts
We're starting to use OWL for modern front-end development, however the router did not allow navigating to paths with a query string in the URL, e.g.
```js
router.navigate({ path: '/tasks/search?query=test&count=20' })
```
did not match the `/tasks/search` path.
Now it does :)
I've added tests. Let me know if you need anything further.
> [IMP] router: allow query string in paths

- src/qweb/extensions.ts
There is a possibility that the transitionend event of an element/component
with t-transition directive won't trigger. Though this situation is
difficult to assert, it was observe in odoo runbot for the pos ui.
When the transitionend event is not fired, the callback that removes
the element from the dom won't be called, resulting to a corrupted view.
An example of which is the following:
```html
<div t-if="show" t-transition="fade">Hello</div>
```
If `show` is set to false by some ui action and by any chance the
transitionend event is not fired (perhaps because the transition didn't
actually start or because of completely unknown reason), the div element
will remain in the view -- and this is not desirable.
This commit patches this situation such that if after 50ms that the
transitionend …
> [FIX] extensions: guarantee to call transitionend callback

- .github/workflows/deploy.yml
- package.json
Node 10.x is no longer maintained, and since a recent commit [1],
a test fails with that version.
[1] 88fd1cf4838b0ea28ea484655dd2aef6a5ec5291
> [FIX] package.json: bump node version to v12

- src/vdom/modules.ts
Port from original snabbdom project:
snabbdom/snabbdom#634
The issue is that before this commit, the removeClass method was sometimes called even if it is not useful. See this comment for more detail: https://github.com/snabbdom/snabbdom/issues/633#issue-618706258
> [IMP] vdom: performance improvement

- src/qweb/qweb.ts
- tests/component/slots.test.ts
In some situations (a slot inside a slot), the combine method was
wrongly copying all properties of the scope into the context, which
caused the event handling system to wrongly use a subobject as component
(since it detects the fact that __owl__ is a own property_).
Consequently, we could have very subtle issue with some properties being
shadowed by a sub object.
> [FIX] slots: make sure handlers are properly bound to component

- src/qweb/expression_parser.ts
- tests/qweb/qweb_expressions.test.ts
Before this commit, Owl inline expressions with a list with multiple
elements such as [a,b,c] was transformed into
[scope['a'], b: scope['b'], scope['c']]
instead of
[scope['a'], scope['b'], scope['c']]
This is due to a previous commit adding support for short object
descriptions such as {a,b}.
To fix this means that we have to keep track of the current group type
for the expression, which is done by using a stack.
> [FIX] qweb: properly handle lists in inline expressions

- src/qweb/qweb.ts
- tests/component/slots.test.ts
The previous changes in the combine method (used to copy all the
variables defined in the current scope for use in a slot) had the effect
of squashing the prototype chain: instead of `Component -> Obj1 ->
Obj2 -> Obj3`, the combined scope had: `Component -> Obj1'`.
This has an unfortunate interaction with the way t-call is implemented,
which uses the fact that we are in a subscope to add a own
__access_mode__. It depends specifially on the prototype chain, and that
the parent scope may have a different value for that property. But with
the way combine was implemented, we lost all that subtlety since
everything is squashed.
In this commit, we reimplement that function in a way to make sure we
keep the prototype chain structure
> [FIX] slots: fix bad interaction between t-call and slots

- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb_t_att.test.ts.snap
- tests/qweb/qweb_t_att.test.ts
Previously, if two attributes in t-att-class shared some classes, their
presence would be determined by the last attribute declared, instead of
being present if any attribute containing it evaluates to true. This
commit fixes that.
> [FIX] qweb: fix overlapping multi-class in t-att-class

- src/qweb/base_directives.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/__snapshots__/qweb_memory.test.ts.snap
- tests/qweb/qweb_memory.test.ts
In some very rare cases (such as the use of the t-foreach directive),
Owl did leak the values in the render context in the global context.
This was due to the fact that the compiled template looked like this:
let _3 = _4 = _5;
instead of
let _3 = _5;
let _4 = _5;
> [FIX] qweb: do not leak values in global context in rare cases

- src/component/fiber.ts
Currently in some cases, adding an attachment via lognote creates a traceback.
Error : shouldPatch is true while `vnode` is not defined, so `patch()` failed
This is a hotfix correcting this problem by calling `patch()` only if `shouldPatch` is true **and** the `vnode` is set.
opw-2645203
> [FIX] components/fiber: Call patch only if target is valid

- src/qweb/compiler.ts
- src/qweb/inline_expressions.ts
- src/qweb/parser.ts
- src/qweb/template_helpers.ts
- src/refs.ts
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/style_class.test.ts.snap
- tests/components/error_handling.test.ts
- tests/components/hooks.test.ts
- tests/components/refs.test.ts
- tests/components/slots.test.ts
- tests/components/style_class.test.ts
- tests/misc/portal.test.ts
Refs to component expose a lot of implementation details that should be
private to parents. Parent to child communication should go through
props.
> [IMP] qweb/components: remove t-ref on components

- src/component/component_node.ts
- src/component/error_handling.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
Have a Child Compnent which has one component that succeeds and another
one that fails at its instanciation.
The Child component handles the Errors by rendering itself.
Before this commit, the error handling algorithm made impossible for the scheduler to finish.
This was because the current fiber was still counted as ongoing, when it was actually completed.
After this commit, this use case is handled correctly.
> [FIX] component: error_handling on current component

- src/component/error_handling.ts
- src/component/fibers.ts
- src/component/scheduler.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
Before this commit, errors triggered at the level of the fiber (as opposed to at the level
of a component's rendering), were handled as the very top level of the rendering, that is,
in the scheduler.
This was wrong because components below in the rendering tree would not have a chance to handle their
children's or their own errors.
After this commit, error triggered in willPatch, onMounted and onPatched are correctly handled
at the closest component to where they were thrown.
> [FIX] component, fiber: error_handling at the Fiber level

- src/blockdom/block_compiler.ts
- tests/blockdom/block.test.ts
Before this commit, there were situations where the reference numbers
were not properly set, which caused the blocks generated to crash
because the algorithm could not get correct references.
> [FIX] blockdom: properly handle references

- src/app/app.ts
- src/component/error_handling.ts
- src/component/lifecycle_hooks.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
Before this commit, class inheritance when using the onError hook was unclear nay wrong.
After this commit, error handlers are called from the bottom up  in the inheritance hierarchy.
If a handler doesn't rethrow the error, the handling stops there and no other handler is called.
If a handler does rethrow, the handlers declared in a parent class are executed.
> [FIX] component: error handling in class inheritance

- src/qweb/compilation_context.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
When fixing the absence of capture for arrow functions passed as props,
we unintentionally introduced a breaking change: bare function calls in
the arrow functions used to be called  with the rendering context as
their this value and this was no longer the case.
This commit fixes that by intentionally not capturing the value of
functions that are called withing the arrow function.
> [FIX] component: make arrow-function capture backwards compatible

- src/component/component_node.ts
- src/component/fibers.ts
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/concurrency.test.ts
Have a child component on which a render is triggered.
This component delays its willUpdateProps and makes a rendering during the willUpdateProps
Before this commit, renderings of the child were inconsistent across
its parent's renderings.
After this commit, it works as expected.
> [FIX] component: render in delayed willUpdateProps

- src/qweb/qweb.ts
- tests/qweb/qweb.test.ts
Since commit
https://github.com/odoo/owl/commit/b2f12a111524f37348b142ac248813f9cb25ca2e,
Owl escape text content twice. It seems that it was done to prevent
security issues, but without realizing that the standard t-esc method
already escapes.
closes #708
> [FIX] qweb: renderToString should not escape twice text content

- src/blockdom/attributes.ts
- tests/blockdom/block_attributes.test.ts
This commit fixes some issues with falsy attributes not being properly
set/removed in various situations
> [FIX] blockdom: properly handle falsy attributes

- src/component/component_node.ts
- src/component/fibers.ts
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/concurrency.test.ts
- tests/components/lifecycle.test.ts
Have a component which does a render in its onWillPatch, onPatched, onMounted hooks.
Before this commit, the result was incorrect: the second rendering was not taken into account.
After this commit, those renderings are correctly applied.
> [FIX] fiber, lifecycle: trigger a render during the fiber.complete

- src/portal.ts
- tests/misc/__snapshots__/portal.test.ts.snap
- tests/misc/portal.test.ts
Before this commit, the props validation would fail in dev mode because
it did not expect a slot prop.
> [FIX] portal: do not crash in dev mode

- src/portal.ts
- tests/misc/__snapshots__/portal.test.ts.snap
- tests/misc/portal.test.ts
Before this commit, Portal overrode the _render function for its
component node, which means it bypassed the error handling mechanism
that was implemented in that method.  It could have been fixed by
duplicating the error handling code as well, but a better solution in my
opinion is to simply override the renderFn function.  This is closer to
the actual intent of the portal implementation: wrap the result of the
rendering in a VPortal vnode.
> [FIX] portal: properly handle errors

- src/compiler/code_generator.ts
Previously, we would replace block declarations in some contexts with
the variable alone, and decalres the variable higher in the generated
code. Issues arise because whe sometimes try to replace "let b2" with
"b2" but end up matching "let b20" which is incorrect.
This commit fixes that by adding a space to the text that we are trying
to match ("let b2 " won't match "let b20")
> [FIX] code_generator: stop matching other variables prefix

- src/component/lifecycle_hooks.ts
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/lifecycle.test.ts
Before this commit, some of the callbacks were bound to the component
and some were not.
This commit makes all the callbacks bind to the component.
> [FIX] bind lifecycle callbacks to component

- src/component/component.ts
- tests/components/__snapshots__/t_props.test.ts.snap
- tests/components/t_props.test.ts
- useState returned a Reactive, which is true, but in practice makes it
difficult to use outside of internal code for owl
- Component class was no longer generic, which prevented application
code to be properly typed
> [FIX] typescript: 2 typing issues

- src/app/app.ts
- src/component/scheduler.ts
This is useful to prevent interactions with other testing code.
> [REF] scheduler: capture requestAnimationFrame asap

- src/compiler/code_generator.ts
- tests/components/__snapshots__/basics.test.ts.snap
- tests/components/__snapshots__/t_props.test.ts.snap
- tests/components/t_props.test.ts
The child receiving the props can observe changes made to the passed
t-props object which is not desirable.
> [FIX] compiler: do not pass dynamic props object as is

- src/component/lifecycle_hooks.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
Previously, a crash in a lifecycle hook for any reason would throw an
error whose stack trace started from the scheduler and contained only
the place where the hook was called by owl, but not the place where the
hook was registered by the user. This proved very difficult for users to
debug as they cannot really tell which component registered that hook.
This commit alleviates the issue by creating a new Error when the hook
is originally called, and wrapping the registered callback in a try
catch, throwing an error with the correct stack trace instead of the
error in the hook, and setting the error in the hook as the cause of
this synthetic error.
> [IMP] component: improve errors when thrown from lifecycle hooks

- src/app/app.ts
Before this commit, it was logged for every app created, which is
annoying in odoo: because of the compatibility layer, there are many
apps being created.
> [IMP] app: only log dev message once

- src/component/component_node.ts
- src/reactivity.ts
This allows to see which objects and which keys in those objects a
component is observing, so that issues with missing renders or extra
renders can be more easily diagnosed.
> [IMP] component, reactivity: add subscription getter in dev mode

- src/hooks.ts
- tests/components/__snapshots__/hooks.test.ts.snap
- tests/components/hooks.test.ts
Before this commit, if the effect function would throw, then the cleanup
function would not be properly assigned, which caused additional errors
later, when the cleanup code would try to call it.
closes #1149
> [FIX] useEffect: properly handle errors in effect function

- doc/reference/app.md
- src/component/lifecycle_hooks.ts
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/lifecycle.test.ts
- tests/helpers.ts
This commit adds a warning when an async hook
(onWillUpdateProps/onWillStart) takes longer than 3 seconds, as these
hooks block the rendering and patching of the application, it is rarely
desirable and often a sign of a deadlock. This warning will contain the
stack trace of the call to the hook to help in debugging.
> [IMP] component: emit warning when async hooks take too long

- src/blockdom/attributes.ts
- tests/blockdom/block_attributes.test.ts
In 3536f41f001ea8a0ccb9114b7c2659e3627dadc6 we added a fallback when setting a
property to a falsy value so that the property was set to the empty string. The
objective being to not get the string "undefined"/"null"/"false" as property
value. However, using t-att- to set a property to 0 is perfectly reasonable and
in fact quite common.
> [FIX] blockdom: t-att- correcltly sets the value to zero

- src/reactivity.ts
- tests/reactivity.test.ts
This crash was caused by the fact that Proxies *must* return the value of the
property on the target when that property is non-writeable and
non-configurable. Since the reactivity system always attempts to proxify the
value from the target, this crashes.
This commit fixes that by not proxifying such values. This however means that
from that point on, we have escaped the reactivity system and will not
subscribe to any changes in that object or its children.
closes #1158
> [FIX] reactivity: do not crash when reading reactive frozen objects

- src/utils.ts
- tests/reactivity.test.ts
- tests/utils.test.ts
Previously, calling the batched function from within the callback being
batched would fail as it would be treated as part of the same batch.
This commit fixes that by scheduling the reset of the "called" flag
before calling the callback. This means that all microtasks that were
already in the microtask queue when a batch is about to run are treated
as part of the batch, and all microtasks that will be added by the
callback are not.
> [FIX] utils: fix calls to batched callback from within the callback

- doc/reference/component.md
- src/component/component.ts
- src/component/component_node.ts
- tests/components/__snapshots__/rendering.test.ts.snap
- tests/components/rendering.test.ts
With this commit, we make sure that the `render` method was explicitely
called with the deep === true argument, instead of assuming that it is a
boolean.  This prevents errors when some unrelated value is given to the
render method. This could happen in some cases, such as
useBus(someBus, 'someevent', this.render)
In that case, the `useBus` code would simply call the this.render with a
customevent, which would be considered truthy before, and not anymore
> [FIX] component: strict check of deep argument truth value

- src/component/fibers.ts
- src/component/scheduler.ts
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/concurrency.test.ts
- tests/helpers.ts
Previously, if a fiber was delayed because one of its ancestors was
rendering, and that fiber was not a root fiber, it would be rendered
after all its ancestors had finished rendering even if one of those
ancestor renderings cancelled it.
This commit fixes that by simply checking that a delayed fiber is still
its component node's current fiber before rendering it.
> [FIX] concurrency: do not render delayed fibers when cancelled

- src/app/template_set.ts
- tests/compiler/error_handling.test.ts
- tests/compiler/validation.test.ts
Previously, we used an option to allow duplicate templates, if that
option was passed, we would always replace the existing template with
the new template, and if it wasn't, we would always throw an error even
if the template's content was the same.
Allowing to replace a template with a different one is problematic, as
it may or may not have already been compiled, which may cause various
problems. On the other hand, if the template is the same, there is no
point in throwing an error, as we can just silently ignore the second
addition.
> [IMP] app: allow duplicate templates iff they are the same

- src/compiler/code_generator.ts
- tests/misc/__snapshots__/portal.test.ts.snap
- tests/misc/portal.test.ts
Before this commit, the value of the `t-portal` directive was inserted
in the compiled template without being processed.
> [FIX] portal: allow use of expression to describe portal target

- src/compiler/code_generator.ts
- tests/components/__snapshots__/t_on.test.ts.snap
- tests/components/t_on.test.ts
Before this commit, there were 2 different ways of generating variable
identifiers. And it was possible to have a situation with two different
variable in a template with the same identifier, which caused a crash.
This commit ensures that we go through a unique helper method, so this
cannot occur anymore. Also, the code is slightly simpler.
> [FIX] compiler: fix issue with identifiers with same name

- src/component/component.ts
- src/component/component_node.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
If you declare a child component which is not actually a Component,
the error message is not very friendly and not very helpfull to find
what happens and which child component is wrong.
```js
const ChildComponent = "not a component constructor";
class MyComponent extends Component {
static components = { ChildComponent };
}
```
This commit improves the type declaration for those working with Typescript
and adds a runtime check for javascript codebases
> [IMP] component: display nice error for wrong child component

- src/component/props_validation.ts
- tests/component/props_validation.test.ts
- tests/misc/portal.test.ts
With this commit, props validation error messages will include a more developer-friendly error message, avoiding the need to investigate in the Developer Tools why a complex props structure is invalid.
> [IMP] props_validation: have clearer error messages

- doc/reference/reactivity.md
- src/app/template_helpers.ts
- src/component/component_node.ts
- tests/components/__snapshots__/reactivity.test.ts.snap
- tests/components/reactivity.test.ts
Previously, components would automatically call useState on their props,
so that changes deeply within props would automatically cause the
component to be rendered. This can be useful when passing a piece of
state to children or descendants.
One problem with this is that all props implicitly become reactive, even
if the object that was passed as a props was not. The problem with that
being that since the original object is not reactive, any change made by
the parent will not go through the reactivity system and the children
won't be notified of the change, in essence, this reactive object is
essentially useless, while having a real cost: traversing reactive
objects creates more reactive objects, and those objects are all
proxies. This is expensive for basically no benefit, while also …
> [IMP] component: only useState on props that are already reactive

- src/compiler/inline_expressions.ts
- tests/compiler/inline_expressions.test.ts
Previously, the support for the "in" operator was iffy, and "new" was
not supported at all, "in" would fail when checking if a nested property
was in something else, as the leading space would be stripped, and "new"
would fail because the following space would be stripped.
This commit fixes that by preserving the significant whitespace where
necessary.
> [IMP] compiler: add better support for "in" and "new" operators

- doc/reference/props.md
- src/runtime/validation.ts
- tests/validation.test.ts
This commit add supports for value types in prop validation. To describe
a value V type, one has to simply write {value: V}.
Note that this commit also improves the validation typing.
closes #1198
closes #910
> [IMP] validation: add support for value types

- src/runtime/blockdom/attributes.ts
- tests/compiler/__snapshots__/attributes.test.ts.snap
- tests/compiler/attributes.test.ts
Previously, having a leading or trailing space caused
HTMLElement.classList.add to be called with an empty string (because we
are splitting on whitespace), which is not allowed and caused a crash.
This commit fixes that by trimming the keys of the class object in the
same way that we already do it for class strings.
> [FIX] blockdom: fix crash when class object key has leading spaces

- src/runtime/error_handling.ts
- src/runtime/lifecycle_hooks.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
Previously, when wrapping errors in wrapError, if the error was not an
actual error object, we wouldn't set the cause property on the wrapping
error correctly. The "instanceof Error" check is simply there so that we
can know whether we can add the original errors message to the wrapping
error, but the line that sets the error's cause was mistakenly moved
into that condition.
This commit also fixes the wrapping error's message in the case of
non-Error objects, to avoid having "the following error occurred in
hookname:" with nothing after the colon which is confusing/misleading.
> [FIX] components: fix cause left unset when thrown object is not Error

- src/runtime/index.ts
We have been using this type in o-spreadsheet since https://github.com/odoo/o-spreadsheet/pull/1187
but the new typing file (https://github.com/odoo/owl/pull/1207) does not include it.
It would be useful to allow us to bump or version of owl witouht having to resort
to long aboslute paths (i.e. import from `@odoo/owl`and not
`@odoo/owl/dist/types/runtime/component@ everywhere).
> [IMP] types: expose ComponentConstructor for typing purpose

- src/compiler/code_generator.ts
- tests/compiler/__snapshots__/attributes.test.ts.snap
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/attributes.test.ts
Recently, we made it so that when a component is rendered, it always
updates the property values for computed properties. This was done by
wrapping the value in a String or Boolean object. One issue with this is
that wrapping a falsy value in a String doesn't yield an empty string,
but a string containing the value as text (eg new String(undefined) ->
"undefined"), which causes the value to not remain empty as per the
spec. This commit fixes that by adding a fallback to the empty string
for falsy values before converting to a String object.
> [FIX] compiler: fix falsy values for properties not keeping input empty

- src/runtime/utils.ts
- tests/app/__snapshots__/app.test.ts.snap
- tests/app/app.test.ts
Previously, attempting to mount an app in an iframe would crash, saying
that the target is not a valid DOM element, this is because instanceof
checks do not work cross-frame as global objects do not have the same
identity in frames as with the main window. This commit fixes that by
making sure the target is an instance of HTMLElement of the
corresponding window, and checks that the corresponding document body
contains it.
> [FIX] app: allow mounting owl apps in iframe

- src/runtime/blockdom/events.ts
- tests/components/__snapshots__/event_handling.test.ts.snap
- tests/components/event_handling.test.ts
Previously, event handlers would not work when an app was mounted in an
iframe, this is caused by a guard in the event handler that checks that
the target element is still in the document, but it doesn't check
against the correct document in the case of an iframe.
This commit changes the check to check against the target's
ownerDocument.
> [FIX] events: correctly call handlers in iframes

- doc/learning/tutorial_todoapp.md
In app.js, `mount(Root, document.body, { dev: true, env });`  crash because `body` is not available yet. 
Therefore, moving the script into the body fix the issue.
> [FIX] tutorial_todoapp: fix the final code mount issue

- src/runtime/app.ts
- src/runtime/component_node.ts
- src/runtime/error_handling.ts
- src/runtime/fibers.ts
- tests/components/basics.test.ts
- tests/components/error_handling.test.ts
- tests/components/hooks.test.ts
- tests/components/props_validation.test.ts
- tests/components/refs.test.ts
- tests/components/slots.test.ts
- tests/components/style_class.test.ts
- tests/components/t_foreach.test.ts
- tests/helpers.ts
- tests/misc/portal.test.ts
This commit makes it so that when an error occurs in an owl app and none of the registered error handlers are able to handle it, we rethrow the error instead of just logging it to the console and swallowing it. This allows users of owl to handle errors that happen in owl applications by using event listeners for error and unhandledrejection events on the window.
> [IMP] app: rethrow errors that were not handled

- doc/reference/hooks.md
The `useEffect` has two parameters:
* The `effect` function
* The `computeDependencies` function
The `effect` function always take as parameters the result
of the `computeDependencies` function.
Expliciting this allows to better understand the `useEffect` behaviour and the following example in the doc:
```js
useEffect(
(el) => el && el.focus(),
() => [ref.el]
);
```
> [IMP] doc: explicit `useEffect` first parameter

- src/runtime/blockdom/block_compiler.ts
When creating the template node for a block, we create htmlelements and set their (static) attributes.  But this can have side effects. For example, setting the src attribute for an img element will trigger a request to fetch the image.
We avoid that issue by simply setting the html element template node inside a <template/> element.
Note that I don't really see how to test this fix in jest: we don't have a real browser, and no real way to check for this side effect.
closes #1257
> [FIX] blockdom: prevent side effects at block compilation

- src/compiler/code_generator.ts
- src/runtime/app.ts
- src/runtime/template_helpers.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/__snapshots__/props_validation.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/__snapshots__/t_foreach.test.ts.snap
- tests/components/t_call.test.ts
The code for props validation assumed that the rendering context was a component.  This was actually true when it was written, but is no longer true since t-call-context was introduced.
Because of that, it would crash when trying to access the internals of the component, such as the static components object.
The fix is simple: instead of passing the context to the props validation code, which can now be anything, we pass the component node, which is guaranteed to give a reference to the component (and also to the app).  This also make the code slightly simpler.
closes #1261
> [FIX] props validation: does not crach with t-call-context

- src/compiler/code_generator.ts
- tests/components/__snapshots__/t_foreach.test.ts.snap
- tests/components/t_foreach.test.ts
Currently when checking for duplicate keys, we insert the value of the key as is in a set then check for unicity against those. When the key is an object, we check for duplicates based on object identity, whereas the keys are used by owl as strings, and so using objects can cause duplicate key errors that do not throw correctly but crash in the owl internals.
This commit fixes that by making the duplicate checking code serialize the key to string before insertion and when comparing against existing keys.
> [FIX] runtime: correctly throw an error for duplicate object keys

- src/compiler/parser.ts
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/slots.test.ts
Currently, if a component has a default slot defined with t-set-slot, and also content that compiles to something (eg, text or even a comment node), the content takes priority over the t-set-slot. As t-set-slot is more explicity, it should have priority.
> [FIX] parser: give t-set-slot="default" priority over the content

- src/runtime/blockdom/block_compiler.ts
- src/runtime/blockdom/event_catcher.ts
- src/runtime/blockdom/html.ts
- src/runtime/blockdom/index.ts
- src/runtime/blockdom/list.ts
- src/runtime/blockdom/multi.ts
- src/runtime/blockdom/text.ts
- src/runtime/blockdom/toggler.ts
- src/runtime/component_node.ts
- src/runtime/portal.ts
- tests/components/__snapshots__/t_foreach.test.ts.snap
- tests/components/t_foreach.test.ts
Currently, the `moveBefore` method on VNodes assumes that the `other`
VNode it receives is of the same type, and that the entire VNode tree
below that other VNode has the exact same structure. While this is
correct in most cases, it breaks down when there is a VToggler somewhere
in the VNode tree, as the structure below a VToggler can be very
different from the structure below another VToggler that was created
from the same compiled code. For example, two iterations of a t-foreach
that contains a <t t-component="..."/> may spawn different components,
and different components obviously have different structures.
One way to fix this is to remove the assumption that the structure of
the `this` block tree in moveBefore is the same as the structure
of the `other` block tree, and instead, …
> [FIX] blockdom: correctly reorder children in heterogeneous t-foreach

- src/runtime/blockdom/block_compiler.ts
- src/runtime/blockdom/event_catcher.ts
- src/runtime/blockdom/html.ts
- src/runtime/blockdom/index.ts
- src/runtime/blockdom/list.ts
- src/runtime/blockdom/multi.ts
- src/runtime/blockdom/text.ts
- src/runtime/blockdom/toggler.ts
- src/runtime/component_node.ts
- src/runtime/portal.ts
- tests/misc/portal.test.ts
Previously, when trying to mount a portal into a target that would be mounted in the same render as the portal itself, the portal content could not be mounted correctly. In a previous attempt to fix it, a mistake was made while writing the test causing us to incorrectly believe in now worked, when in fact, it would just move the portal content to the end of its parent but without changing it.
This commit fixes the issue by making the `moveBeforeDOMNode` method of VNodes accept a second optional parameter which is the parent in which the element should be moved, defaulting to the current parent. This results in identical behaviour when a parent is not specified, but when it is, the VNode is "reparented" to the passed parent, which is what is now done by the Portal
> [FIX] portal: correctly move portal content when target is after it

- src/runtime/app.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
This PR adds a better error message when the components key is missing in a parent component with static subcomponents. Should resolve #1283
> add a better error message when components key is missing in parent

- src/compiler/code_generator.ts
- src/runtime/template_helpers.ts
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/__snapshots__/t_ref.test.ts.snap
- tests/compiler/t_ref.test.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/hooks.test.ts.snap
- tests/components/__snapshots__/props.test.ts.snap
- tests/components/__snapshots__/props_validation.test.ts.snap
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/__snapshots__/t_foreach.test.ts.snap
- tests/components/__snapshots__/t_on.test.ts.snap
- tests/components/__snapshots__/t_set.test.ts.snap
- tests/components/t_call.test.ts
- tests/helpers.ts
- tests/misc/__snapshots__/portal.test.ts.snap
With the introduction of t-call-context, there is now no guarantee that
the ComponentNode can be found in the rendering context, any attempt to
do so can crash when combined with t-call-context. This commit fixes
that by using `this` instead, which in compiled templates refers to the
component that is being rendered.
> [FIX] compiler: do not look up ComponentNode in the context 

- src/compiler/code_generator.ts
- tests/components/__snapshots__/t_model.test.ts.snap
- tests/components/t_model.test.ts
With this commit, we make sure that the code for t-model is run before t-on-input event handler.  This is useful to make sure that the state reflected by t-model is up-to-date.
closes #1295
> [FIX] t-model takes precedence over t-on-input

- src/runtime/component_node.ts
- src/runtime/index.ts
- src/runtime/reactivity.ts
- tests/reactivity.test.ts
Previously, when there was a reactive object in the prototype chain of a different object, it would get notified of the first write to a property that existed on the reactive object but did not yet exist on the other object, despite the value of that property not actually getting written to the reactive and hence the value not getting changed.
This was caused by the fact that we assumed that Reflect.set would set the value on the target, when in fact, the value is set on the object that underlies the `receiver`. When a reactive object is part of the prototype chain, the first write on a key triggers the set trap but the receiver is not the reactive object, and so Reflect.set doesn't modify the target, but adds the new key to the object that's lower in the prototype chain.
This commit …
> [FIX] reactivity: fix issues with reactive objects in proto chain

- src/runtime/reactivity.ts
- tests/reactivity.test.ts
When attempting to create a reactive object, we first check if the target can be made reactive, this is done with Object.toString, which internally reads the Symbol.toStringTag on the underlying object. When trying to make a reactive object from another, for example when reobserving a reactive or when reading a reactive object from the context of another, this would read the subscribe the original object to the Symbol.toStringTag property.
This commit fixes that by calling Object.toString on the underlying target object where applicable.
> [FIX] reactivity: don't subscribe to keys when making reactive

- src/compiler/code_generator.ts
- src/runtime/template_helpers.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/__snapshots__/t_foreach.test.ts.snap
- tests/components/__snapshots__/t_on.test.ts.snap
- tests/components/__snapshots__/t_set.test.ts.snap
- tests/components/t_call.test.ts
- tests/misc/__snapshots__/portal.test.ts.snap
Previously, when using a component with a slot within a t-call with t-call-context, the component would become available again inside the slot despite the t-call-context. This was caused by the fact that the capture helper function creates an object with the component as its prototype which is incorrect. It should just use the previous context as its prototype.
> [FIX] t-call-context: fix capture making component available in ctx

- doc/learning/tutorial_todoapp.md
- doc/reference/templates.md
- src/compiler/inline_expressions.ts
- src/runtime/component_node.ts
- tests/compiler/__snapshots__/event_handling.test.ts.snap
- tests/compiler/event_handling.test.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/style_class.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/__snapshots__/t_on.test.ts.snap
- tests/components/t_call.test.ts
- tests/misc/__snapshots__/portal.test.ts.snap
t-call-context is a feature that's supposed to mask the rendering
context completely, but currently the component remains available
through `this`.
This commit stops treating `this` as a reserved word, so that it's
compiled to a lookup in the rendering context, and adds `this` to the
rendering context when binding the component's rendering function. With
these changes, `this` behaves the same as before when outside a
t-call-context, but when the rendering context is overriden, the
template can no longer access `this`. `this` still represents the
instance of the component inside of the rendering function since it's
needed by owl internally.
> [FIX] t-call-context: make this unavailable in rendering context

- src/compiler/code_generator.ts
- tests/components/__snapshots__/t_model.test.ts.snap
- tests/components/t_model.test.ts
Have a radio group defined inside a t-foreach:
```xml
<t t-foreach="values" t-as="val" t-key="val">
<input name="radiogroup" t-att-value="val" t-model="state.radioGroup" />
</t>
```
Before this commit the algorithm that set the "checked" attribute on the current active radio button according to the state did not support having a dynamic value (`t-att-value`)
After this commit, this use case works as we go look in the dynamic attributes too.
closes #1294
> [FIX] compiler: t-model supports radio group in t-foreach

- tools/release.js
Previously, if you were not the last person to publish to the playground, your playground branch would be behind the remote and trying to push to it would fail.
This commit attempts to pull the changes before updating owl so that even if you were not the last person to push to the playground, as long as the pull is a fast-forward, publishing to the playground won't fail.
This commit also adapts some of the status number manipulation to use bitwise or instead of addition, since return status code can be both positive or negative and may cancel one another. Using bitwise or ensures than any non-zero code will make the status non-zero and stay that way.
> [IMP] tools: pull playground before trying to publish

- tools/compile_xml.js
Compiling a template with a dash ("-") in its name generates an invalid function name in the compiled code.
A template named `"my-component"` leads to the function `function my-component(app, bdom, helpers) { ... }` which has an invalid name.
closes #1333
> [FIX] tools: allow to pre-compile templates with - in their name

- src/hooks.ts
[FIX] hooks: fix useRef in Firefox 109+
Since Firefox 109, appending an HTMLElement into an iframe changes the
prototype of that element from the HTMLElement of the window where it
was created to the HTMLElement of the window of the iframe into which it
is appended. This causes the `instanceof HTMLElement` check in `useRef`
to fail, as `HTMLElement` refers to the window in which owl is declared.
This commit fixes that by adding an extra `instanceof` check that uses
the element's ownerDocument window.
> [FIX] hooks: fix useRef in Firefox 109+

- src/compiler/code_generator.ts
- tests/components/__snapshots__/basics.test.ts.snap
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/t_component.test.ts.snap
- tests/components/concurrency.test.ts
Previously, if the value of a t-component directive changed, but there was already a scheduled render for the component before that change, the rendering of the existing component would get delayed (as it should), but after the parent's rendering was complete, the old component which will be destroyed during the patch would still get rendered, despite being stale. This can cause crashes if that component relies on state that no longer exists.
This was caused by the fact that when rendering, we check the parent chain for an active render, and also check that the component still exists in the parent's fiber childrenMap (ie, we know that the upcoming patch is not about to destroy the component). To do this, we use the component's parentKey, but in the case of t-component, the parentKey for …
> [FIX] components: stop rendering stale t-component when delayed

- src/runtime/reactivity.ts
- tests/components/__snapshots__/reactivity.test.ts.snap
- tests/components/reactivity.test.ts
Previously, the getSubscriptions debugging utility returned all observed keys for a given target, instead of only the keys observed by the callback it received as argument. This commit fixes that issues.
> [FIX] reactivity: only show key in subscription if observed by callback

- src/runtime/validation.ts
- tests/components/__snapshots__/props_validation.test.ts.snap
- tests/components/props_validation.test.ts
In dev mode, owl inserts an additional props validation step. Before this commit, the validation would iterate on all key/value pairs of each props. If the props is reactive, this has the unfortunate side effect of subscribing the component to each of the keys, even though it should not be.
This commit avoids the issue by only validating the raw object.
> [FIX] props validation: do not subscribe to props keys

- src/runtime/app.ts
The devtools extension needs to hook itself into some internal functions of owl, and to do that, it needs a reference to Fiber and RootFiber classes.
> [IMP] devtools: provide access to Fiber and RootFiber

- src/compiler/code_generator.ts
- src/runtime/template_helpers.ts
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/__snapshots__/t_ref.test.ts.snap
- tests/components/__snapshots__/hooks.test.ts.snap
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/refs.test.ts
Have a t-ref on a DOM node with a t-key.
Change the t-key.
Before this commit, the old block removed its element from the component's refs *after* the new block had been mounted, meaning that in effect, the resulting ref at the end of the whole patch was null.
After this commit, we only remove an element from the component's ref if that very same element was indeed the ref. (otherwise it means someone else has changed the ref.)
> [FIX] compiler: t-key and t-ref together

- src/compiler/code_generator.ts
- tests/compiler/__snapshots__/attributes.test.ts.snap
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/attributes.test.ts
- tests/components/__snapshots__/t_model.test.ts.snap
In #1161, we fixed blockdom treating 0 as falsy when patching a value, which would result in an empty attribute. It turns out that there is another place where we had the same fallback, which is when we compute a dynamic attribute value, so while blockdom had the ability to set the value to 0, when using a dynamic attribute value we would never give it 0 as a value. This commit changes the fallback strategy for dynamic attribute values to be the same as the one in blockdom.
closes #1358
> [FIX] compiler: dynamic value on inputs doesn't turn 0 into empty string

- src/compiler/code_generator.ts
- src/compiler/parser.ts
- tests/compiler/__snapshots__/translation.test.ts.snap
- tests/compiler/parser.test.ts
- tests/compiler/translation.test.ts
Before this commit, the parser would remove all consecutive white spaces for text nodes. After that, the code generator would call the translate function with the resulting string, which then is different than what we would expect.
With this commit, we make sure we apply the translation before removing the additional whitespace. To do that, we have to move the code processing the string from the parser into the code generator, which actually makes sense, as the parser should only collect all useful information without applying too much logic.
closes #1351
> [FIX] compiler: call translate function with correct string

- src/compiler/code_generator.ts
- src/runtime/component_node.ts
- src/runtime/template_helpers.ts
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/refs.test.ts
- perform the check at render time instead of patch time => no need to register lifecycle hooks
- zero cost abstraction in prod mode
> simplify (?) multiple ref checking

- src/compiler/code_generator.ts
- src/runtime/component_node.ts
- src/runtime/hooks.ts
- src/runtime/template_helpers.ts
- tests/app/app.test.ts
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/__snapshots__/t_ref.test.ts.snap
- tests/compiler/t_ref.test.ts
- tests/components/__snapshots__/hooks.test.ts.snap
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/refs.test.ts
Previously, refs could get set to null incorrectly, or could stay set when they shouldn't. This was caused by the fact that singleRefSetter and multiRefSetters are created on every render, meaning that any render that did not affect the status of the ref (mounted or not), would overwrite the previous ref setter, including its closure, causing the captured `_el` or `count` to be lost. This means that on a subsequent render that did affect the status of the ref, the singleRefSetter would consider that it did not set the ref, and so shouldn't unset it, causing it to incorrectly stay keep the element, while in multiRefSetter, the opposite problem occured: the count would be 0 on removal, causing it to believe that it was the first call in the corresponding patch that affected the ref, when in …
> [FIX] runtime, compiler: fix refs getting set or unset incorrectly

- rollup.config.js
- src/runtime/app.ts
- src/runtime/index.ts
- src/version.ts
- tools/release.js
Before this commit, the version number was added by the rollup configuration script. It worked, but it meant that there was no robust way to access the version number in many case. For example, what if I have a page with two different version of owl? Or what if one of them uses the ESM module system, and does not export owl as a global object?
This is not really a big deal, but accessing the version number is useful for tooling purpose, so this commit makes it possible to read the version number on each individual App, as a static property.
> [IMP] release: add version number on App

- src/compiler/code_generator.ts
- tests/components/__snapshots__/props.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/props.test.ts
It is not really useful, but it is possible to bind an anonymous function prop. However, with the recent change on how the bind feature works, it now crashes.
This commit makes sure that we properly apply the `bind` operation to the function, and not to the last term of the function.
> [FIX] components: do not crash when binding anonymous function

- src/runtime/lifecycle_hooks.ts
`onWillPatch`, `onWillUnmount`, `onWillDestroy` are synchronous hooks. Owl will not wait any promise return by the callback. Yet, the callback return type includes `Promise<void>`, which is confusing as one might think it means the hooks is async.
> [REF] hooks: avoid confusion for sync hooks

- tools/devtools/src/devtools_app/devtools_window/profiler_tab/profiler_tab.xml
- tools/devtools/src/main.css
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This PR address multiple small bugs that were detected in the early first release of the extension
The first commit adds box-sizing: border-box to the highlight elements created by the devtools on the page. This was making some of the boxes overflow on some pages (like on POS sessions) because the border-box box-sizing was not the default behavior on these pages.
The second commit hides the collapse all button when the profiler is in Events log mode since it doesn't do anything in this case.
The third commit increases the vertical padding of the search bar in order for it to be easier to click on.
> [FIX] devtools: Fix first release's small bugs

- doc/reference/props.md
- src/runtime/index.ts
- src/runtime/validation.ts
- tests/components/props_validation.test.ts
- tests/validation.test.ts
In JS, objects are often used as a mapping that gives fast lookup on the keys, in those cases, the keys themselves are not known in advance, but the values may have a shape that they're expected to follow. This commit adds support for a `values` key in schema for objects, which will be checked against all values in the object during validation.
> [IMP] runtime: allow validating object values using a type description

- tools/playground/app.js
- tools/playground/playground.css
- tools/playground/templates.xml
This is useful to share editable snippets of owl code, which can be used to paste a reproduction for a given issue or give someone an interactive example of some feature.
> [IMP] playground: allow sharing playground links

- doc/reference/hooks.md
Going from owl 1.0 to 2.0, we removed the possibility of having a reference to a component. However, the documentation was not properly updated to reflect that.
> [DOC] remove old references to comp for useRef hook

- doc/reference/slots.md
The value of activeTab should be tab_index rather than tab.
> [DOC] Fix a code bug in the example of slots

- src/runtime/template_set.ts
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/t_call.test.ts
Before this commit, when using a dynamic t-call, it was possible to have a collision between subcomponent keys. This would cause hard to understand owl crash, because owl would incorrectly use the same component instance for two different template location. From owl point of view, one of these component has to be destroyed and the other one should be mounted, so a crash would occur.
The fix is to simply properly key sub components.
> [FIX] components: properly differentiate t-call subcomponents

- docs/index.html
When refactoring the playground to use es-modules, a script that loads owl as a non-module was forgotten in the head of the page and causes an error in the console, as the script is not declared as type="module" despite being an es-module. This script is also useless as owl is loaded by being imported by the counter component in the page.
The importmap has also been moved to the head because of a bug in firefox where importmaps can fail to be taken into account if they are after a script that is not of type="module", see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1833371
Closes #1436
> [FIX] gh-page: fix 'unexpected token export' error on landing page

- src/runtime/app.ts
- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit adapts the behavior of the devtools global hook to get the toRaw and reactive functions from the __OWL_DEVTOOLS__ variable instead of the global owl when it is missing. Also adds the functions to the __OWL_DEVTOOLS__ variable for the former to work. This allows the devtools to work in environments where owl is loaded through ES modules.
Also quickly fixes iframes detection update on page reload.
> [FIX] devtools: Missing global owl

- tools/devtools/manifest-chrome.json
- tools/devtools/src/devtools_app/devtools_window/components_tab/tree_element/tree_element.js
- tools/devtools/src/devtools_app/devtools_window/components_tab/tree_element/tree_element.xml
- tools/devtools/src/devtools_app/store/store.js
This commit adds the functionnality to add components to the toggle blacklist so that it won't be expanded by default when launching or reloading the devtools components tree. Also change chrome devtools version to 1.1 for the webstore.
> [IMP] devtools: Add blacklist to components toggle

- tools/devtools/src/devtools_app/devtools_window/components_tab/details_window/details_window.xml
- tools/devtools/src/devtools_app/devtools_window/components_tab/details_window/object_tree_element/object_tree_element.xml
- tools/devtools/src/devtools_app/devtools_window/components_tab/tree_element/tree_element.xml
- tools/devtools/src/devtools_app/devtools_window/profiler_tab/event/event.xml
- tools/devtools/src/devtools_app/devtools_window/profiler_tab/event_node/event_node.xml
- tools/devtools/src/devtools_app/store/store.js
This commit makes it so the position of the context menu doesn't require an additional render to apply so it fixes the flickering.
> [FIX] devtools: fix context menus flickering

- src/compiler/parser.ts
- tests/compiler/parser.test.ts
Before this commit, the `t-on` directive assumed that the next character would be a -, and ignored it, so if someone would write `t-onclick` by mistake, Owl would then add an event handler on the `lick` event, instead of `click`.
With this commit, we improve the parser to make it stricter and fail if there is no dash.
closes #1441
> [FIX] parser: make t-on stricter

- tools/devtools/src/devtools_app/devtools_window/profiler_tab/event/event.xml
- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/main.css
This commit adds a colored border between events in list view when a new animation frame was created.
> [IMP] devtools: add border for new animation frame

- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit changes the moment when all methods that need patching to handle events are actually patched: the complete method of RootFiber is now patched at devtools startup (when the tab owl tab is opened) and every other method is patched at first activation of the event recording functionality. This makes sure that the devtools will have no impact on performance whatsoever when they are not directly put in use.
> [IMP] devtools: patch app methods only when needed

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit fixes the three following issues:
- Symbols could never appear in shortened display of objects
- Objects which contained only symbols as keys would be considered to be empty and therefore not expandable
- Symbol value edition would create a new property on the object with the stringified symbol as key instead of updating its value 
closes https://github.com/odoo/owl/issues/1464
> [FIX] devtools: fix symbols handling and display

- tools/devtools/src/devtools_app/devtools_window/components_tab/details_window/object_tree_element/object_tree_element.js
- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit first fixes how object prototype are detected so that it won't stop as soon as the constructor name of the object is "Object". This allows displaying every single prototype encountered and closes https://github.com/odoo/owl/issues/1467.
This commit also improves how the env of a component is displayed by expanding its chain of prototypes by default while keeping its keys lit as long as it is their first occurence in the chain.
> [FIX] devtools: fix/imp env display

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit fixes a crash in the retrieval of the components tree which happened when the first app did not contain a root node. The default inspected component is now set to be the first root component found in the apps.
> [FIX] devtools: Fix crash when no root node

- src/compiler/parser.ts
- tests/compiler/parser.test.ts
Before this commit, the template parser would allow using t-esc on a component tag (<MyComponent t-esc="expr"/>) but would incorrectly ignore the component when parsing a t-out: <MyComponent t-out="expr"/> would be parsed as <t t-out="expr"/>
This commit solves the issue, and also, moves the `t-out` parsing code next to `t-esc` so they have the same priority relatively to other directives.
closes #1483
> [FIX] compiler: allow t-out on component tag

- src/runtime/app.ts
- tests/app/__snapshots__/app.test.ts.snap
- tests/app/app.test.ts
Before this commit, the App destroy method would not destroy everything synchronously. The code scheduled a flush, which is asynchronous, to finally clean up the task lists, and destroy the cancelled nodes. But this is not really good for tests: we need a stronger guarantee that nothing will happen after the destroy.
With this commit, we simply call the processTask method immediately after destroying the root component, so all cancelled nodes will be destroyed immediately.
> [FIX] app: sync destroy everythig when app is destroyed

- src/compiler/index.ts
- tests/compiler/validation.test.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
- tests/misc/portal.test.ts
Previously, when a template failed to compile because of a syntax error (typically because we don't do any syntax checking when compiling expression, allowing invalid expressions to be transpiled successfully), the error reporting was very minimal: you would only get the error message itself (eg: "Unexpected token") with the stack information of the error pointing to the call to `new Function` in owl, which is not very useful.
This commit catches the compilation error and completes it with information about the template name when available, and also adds the generated code to the error message, allowing the user to just copy/paste it in their web console or code editor to get a more precise location for the error.
> [IMP] compiler: improve error message when failing to compile template

- src/compiler/code_generator.ts
- tests/app/__snapshots__/app.test.ts.snap
- tests/compiler/__snapshots__/comments.test.ts.snap
- tests/compiler/__snapshots__/misc.test.ts.snap
- tests/compiler/__snapshots__/t_call.test.ts.snap
- tests/compiler/__snapshots__/t_esc.test.ts.snap
- tests/compiler/__snapshots__/t_foreach.test.ts.snap
- tests/compiler/__snapshots__/t_if.test.ts.snap
- tests/compiler/__snapshots__/t_key.test.ts.snap
- tests/compiler/__snapshots__/t_out.test.ts.snap
- tests/compiler/__snapshots__/t_set.test.ts.snap
- tests/compiler/t_call.test.ts
- tests/components/__snapshots__/basics.test.ts.snap
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/higher_order_component.test.ts.snap
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/__snapshots__/props_validation.test.ts.snap
- tests/components/__snapshots__/refs.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/__snapshots__/style_class.test.ts.snap
- tests/components/__snapshots__/t_call.test.ts.snap
- tests/components/__snapshots__/t_model.test.ts.snap
- tests/misc/__snapshots__/portal.test.ts.snap
Because the default content of a t-call is compiled before the block of
the t-call is created, the default content can sometimes incorrectly be
treated as though it is at the root of the template. This causes various
issues, in the case of a t-if, the default content will just replace the
t-call entirely when truthy, and when falsy the template will not return
anything, leading to a crash. Similar things occur with t-foreach and
t-out with a default content.
This commit fixes that by moving the block creation for the t-call ahead
of the compilation of the default content. In doing so, it makes the
context attribute "preventRoot" obsolete: the purpose of this attribute
is to somehow make the code aware that the root of the template will be
defined later, but because it wasn't propagated …
> [FIX] compiler: fix t-call at root of template causing crashes 

- src/compiler/code_generator.ts
- src/compiler/parser.ts
- src/runtime/blockdom/block_compiler.ts
- tests/blockdom/block.test.ts
- tests/blockdom/namespace.test.ts
- tests/compiler/__snapshots__/svg.test.ts.snap
- tests/compiler/svg.test.ts
- tests/components/__snapshots__/basics.test.ts.snap
- tests/components/basics.test.ts
Firefox will not serialize the xmlns attributes of node inside
XMLDocuments, see https://bugzilla.mozilla.org/show_bug.cgi?id=175946
it will only output an xmlns attribute if the node being serialized has
a non-null namespaceURI.
When compiling templates, we currently use a special attribute,
"block-ns" to keep track of the namespace, but we do not make use of the
namespace to create the elements that will be serialized to the compiled
block string. This causes a difference in behaviour between Chrome and
Firefox: since we end up with an Element with two attributes: the
block-ns attribute and the xmlns attribute. Chrome will serialize both,
but Firefox will only serialize the block-ns because the Element does
not have a namespaceURI.
To fix this issue, we get rid of the block-ns magic …
> [FIX] compiler: fix xmlns attribute not being set correctly in firefox

- src/runtime/template_helpers.ts
- tests/compiler/__snapshots__/t_foreach.test.ts.snap
- tests/compiler/t_foreach.test.ts
Previously, support for iterables was added to t-foreach. The idea was that anything that you can spread or on which you can use for..of would be supported. Due to an implementation mistakes, strings, which are iterable were not supported because we checked that the typeof the iterable was 'object'.
To fix this, we coerce the iterable to an object and check whether that coerced value has a Symbol.iterator property, which is what happens behind the scenes when using for..of or spreading a primitive.
Closes: odoo/owl#1503
> [FIX] runtime: properly support t-foreach on strings

- src/runtime/template_set.ts
- tests/compiler/validation.test.ts
When defining a template with a name that the template set already contains, we currently always check whether the template is the same and throw an error when it's not. This is potentially expensive as it can involve serializing a pretty large XML document. This check is only supposed to help during development so this commit disables this check outside dev mode.
> [IMP] runtime: do not check template equality outside dev mode

- src/runtime/app.ts
Before this commit, Owl would export the list of apps in a global object `__OWL_DEVTOOLS__`.  However, it is sometimes useful to be able to access that set, even outside of the devtools (for example, to register templates in all active apps).
closes #1515
> [IMP] app: export apps set as static property

- src/runtime/reactivity.ts
- tests/reactivity.test.ts
Previously, if a reactive was observing the presence of an item in a set that was originally not present, it would get notified when that item was "deleted" from the set (even though there was nothing to delete and the set did not change). The same applied to the key already being present and then being "added". The same thing occured with Map, both for presence but also for values (setting a key to the value it was already set to would notify).
This commit fixes that.
> [FIX] reactivity: do not notify for NOOPs on collections

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit extends the detection of component related dom elements to svg elements in the page so that they can be searched and highlighted correctly with the devtools.
> [IMP] devtools: add svg elements detection

- doc/reference/error_handling.md
A few corrections to make the example more realistic:
- The component has no `error` property, so the writer probably meant `state.error`.
- The "content" slot is not being set, and "default" does the job in this case.
- The closing tag was missing in the `ErrorBoundary`'s template.
> [FIX] doc: error handling example

- doc/reference/component.md
Considering the context, the writer probably meant "onWillDestroy" instead of "onWillUnmount" here.
> [FIX] doc: onWillDestroy mistasken for onWillUnmount

- tools/devtools/src/devtools_app/devtools_window/components_tab/components_tab.js
This commit changes the the minimum width of the subwindows to be fixed so that the icons display stays clean even on very small widths.
> [IMP] devtools: fixed subwindows minimum width

- tests/app/__snapshots__/app.test.ts.snap
- tests/app/app.test.ts
- tests/components/__snapshots__/concurrency.test.ts.snap
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/__snapshots__/t_component.test.ts.snap
- tests/components/basics.test.ts
- tests/components/concurrency.test.ts
- tests/components/error_handling.test.ts
- tests/components/lifecycle.test.ts
- tests/components/props.test.ts
- tests/components/reactivity.test.ts
- tests/components/rendering.test.ts
- tests/components/t_component.test.ts
- tests/components/t_foreach.test.ts
- tests/helpers.ts
- tests/reactivity.test.ts
This allows them to be updated automatically when needed instead of having to update them by hand.
> [IMP] tests: use inline snapshots for lifecycle checks

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit prevents the base object prototype from being unfolded when the env of a component gets unfolded since it does not contain useful information.
> [FIX] devtools: don't unfold env base object prototype

- src/runtime/hooks.ts
- tests/components/hooks.test.ts
`useEffect` type is not compatible with later versions of Typescript.
(I tried with Typescript 5.2, I didn't check which specific
version had the breaking change)
This prevents other projects using owl (such as o-spreadsheet) to upgrade their own version of Typescript.
`<T extends [...T]>` raises the two following errors:
`Type parameter 'T' has a circular constraint.ts(2313)`
`A rest element type must be an array type.`
Also, JSDoc was not working as expected because the type `Effect` was never defined (with `@typedef`).
Hence `@param {Effect<T>} effect` didn't work.
> [FIX] hooks: remove useEffect type circular dependency

- src/runtime/reactivity.ts
- tests/reactivity.test.ts
The purpose of this commit is to not notify reactivity when an object is
replaced by the same object (same reference) in an reactive object.
> [FIX] reactivity: don't react when we set the same object

- tools/devtools/src/main.css
This commit increases the z-index of the context menu so that the border won't be clickable anymore when behind the menu.
> [FIX] devtools: context menu should be above the border

- tools/devtools/manifest-firefox.json
- tools/devtools/src/background.js
- tools/devtools/src/content.js
- tools/devtools/src/devtools_app/devtools.js
- tools/devtools/src/devtools_app/devtools_window/components_tab/components_tab.js
- tools/devtools/src/devtools_app/devtools_window/components_tab/tree_element/tree_element.js
- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/utils.js
This commit fixes 2 issues specific to the firefox version of the extension:
First issue concerns the computation the position of the border between the subwindows of the components tab which could go terribly wrong due to the fact that the innerwidth of the window is implicitly set to 10 when the owl devtools window is hidden. Second issue comes from changes in the runtime.onMessage method of browser which now requires to directly return the response instead of using the sendResponse method.
Also perform a little cleanup on usage of browserInstance and in the manifest.
> [FIX] devtools: fix display and message passing for firefox

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit fixes an issue with the highlight element functionality which would leave the highlight active when the search bar is not empty and the user changes view. It will now disappear as long as the user moves his cursor anywhere in the page. Also, highlights are now removed when the user scrolls while the html selector is active.
> [FIX] devtools: remove highlights when out of devtools

- tools/owl-vision/CHANGELOG.md
- tools/owl-vision/README.md
- tools/owl-vision/package.json
- tools/owl-vision/scripts/owl_template_syntax.mjs
- tools/owl-vision/scripts/syntax_builder_utils.mjs
- tools/owl-vision/scripts/syntax_parts/owl_attributes.mjs
- tools/owl-vision/scripts/syntax_parts/xpath.mjs
- tools/owl-vision/snippets/component.json
- tools/owl-vision/src/extension.ts
- tools/owl-vision/src/search.ts
- tools/owl-vision/src/utils.ts
- tools/owl-vision/syntaxes/owl.template.inline.json
- tools/owl-vision/syntaxes/owl.template.json
This commit adds the following:
- Syntax builder scripts to make syntaxes easier to read and edit
- Syntax highlight in single quote attributes
- Syntax highlight for slot props
- Basic syntax highlight for xpaths
- Added `Switch Below` command
It also fixes the following:
- Using `Switch Besides` or `Switch Below` does not open a new panel if one was already open
- Fixed missing space in component's snippet indentation
> [IMP] owl-vision: syntax scripts, single quotes attributes and slot props highlight and switch below

- src/runtime/template_set.ts
- tests/app/__snapshots__/app.test.ts.snap
- tests/app/app.test.ts
With this commit, the templates that are given while instantiating the App class can be an object with templates not yet parsed (i.e. string, not Document). This allow to instantiate the App class with templates that are not yet parsed, and these templates will be parsed only when needed.
Part of task-id 3601257
> [IMP] app: allow to instantiate templates lazily

- src/runtime/component.ts
- src/runtime/portal.ts
- src/runtime/validation.ts
- tests/components/props_validation.test.ts
Previously, having a Function as a type in the static props description of a component would only work if the component was not the root component, as the static props description on Component was "any", whereas the static props description on ComponentConstructor was "Schema". This meant that static props description on non-root components was not type-checked, and on root components it was type-checked only on the mount call.
This commit makes it so that static type description is of type "Schema" on Component, now causing static props description to be type-checked, and adds `typeof Function` to the `BaseType` union, which allows declaring that a component expects a function as a prop.
Closes #1448
> [IMP] types: correctly support `Function` type for props-validation

- src/common/utils.ts
- src/compiler/parser.ts
- src/runtime/template_set.ts
For some reason the code of parseXML was duplicated, despite being exactly the same except for some whitespace. Move it out into a common utils file.
closes #1569
> [REF] parser, template_set: factor out parseXML function

- src/compiler/parser.ts
- tests/components/__snapshots__/t_model.test.ts.snap
- tests/components/t_model.test.ts
Before to this commit, the .trim modifier did not work correctly. The value in the model is always trim at each input event but not the visual value in the input. This difference between the visual and the model value cause few strange bug.
After reflection, we think that we always want to be in .lazy when we use .trim. Because we want to trim the final value during the onchange event and not at each input event. If we do it at each input event, we can't write more then one word easily.
So this commit change the behavior of the .trim modifier to always be in .lazy
> [IMP] parser: .trim modifier implies .lazy modifier

- doc/reference/app.md
- src/runtime/template_set.ts
- tests/compiler/__snapshots__/template_set.test.ts.snap
- tests/compiler/template_set.test.ts
A template set can now obtain a template by calling the function
getTemplate (if any) received in the initial config.
The returned value can be an Element instance, a template string, a
function (i.e. a compiled template), or null. In the last case, owl will
look into the template set rawTemplates object.
> [IMP] template set config: getTemplate function

- src/runtime/reactivity.ts
While Sets have better lookup complexity than arrays, because of the large constant factors, small arrays can perform better than small sets when checking for inclusion.
In practice, replacing both of the raw types sets with arrays can improve performance of reactive-heavy workloads by as much as 30%.
Considering the reactivity code is very hot when rendering data-heavy components, and the low impact on readability of the fix, the cost-benefit analysis is clearly in favour of making the fix.
> [IMP] reactivity: replace sets with small arrays for performance

- tools/owl-vision/snippets/component.json
- Adds a basic XML owl template
- Make use of `$TM_FILENAME_BASE` and `$RELATIVE_FILEPATH` and attempt to predict the component and template names.
See: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables
> [IMP] owl-vision: Better snippets

- doc/reference/props.md
Missing closing parenthesis in props validation code example
> [FIX] Typo docs

- docs/playground/playground.js
- src/compiler/code_generator.ts
- tests/compiler/__snapshots__/comments.test.ts.snap
- tests/compiler/__snapshots__/simple_templates.test.ts.snap
- tests/compiler/__snapshots__/t_esc.test.ts.snap
- tests/compiler/__snapshots__/t_set.test.ts.snap
- tests/compiler/comments.test.ts
- tests/compiler/simple_templates.test.ts
- tests/compiler/t_esc.test.ts
- tests/compiler/t_set.test.ts
This PR contains two commits that fix incomplete or inexistant escaping of strings that were injected into constructed template literals. See the individual commits for details.
> [FIX] playground, compiler: correctly escape template literals

- src/compiler/inline_expressions.ts
- tests/compiler/inline_expressions.test.ts
This commit fixes inline expressions when we have these conditions:
* inline expression that contains an arrow function
* inside the arrow function call a function with multiple arguments (3+)
* the second argument (not the first and not the last) must be a variable
In the `compileExprToArray` we have a code to handle missing tokens in an object
e.g.: {a} (equivalent to {a:a})
When OWL match all 3 conditions listed above we execute the code to handle the missing tokens and so it alter the tokens and adds a new token: `{ type: "COLON", value: ":" }`
This result in a Javascript compilation error:
OwlError: Failed to compile template "XXX": missing ) after argument list
To fix the error and avoid execute the code to handle the missing tokens, now, we track also the parentheses in our local …
> [FIX] compiler: better support for arrow function and function call

- doc/reference/props.md
- doc/reference/slots.md
- src/compiler/code_generator.ts
- tests/components/__snapshots__/props.test.ts.snap
- tests/components/__snapshots__/slots.test.ts.snap
- tests/components/props.test.ts
- tests/components/slots.test.ts
Previously, if you wanted to pass a prop and have it be translated, you had to either to the translation manually in JS, or use a workaround with t-set and a body so that Owl would translate it for you, and then pass the t-set variable as a prop. This is quite inconvenient and is a common use case.
This commit introduces the `.translate` suffix to solve this issue. When a prop uses this suffix, it is treated as a string instead of a JS expression, avoiding the need for quotes as well as their escaping and allowing extraction tools such as babel to generate a clean string as the term's translation id. This is also more ergonomic.
This change will still require some work in Odoo to correctly extract the terms for props using this suffix.
Odoo PR adding extraction for the suffix: …
> [IMP] compiler: add support for the `.translate` suffix

- src/runtime/lifecycle_hooks.ts
- tests/components/__snapshots__/lifecycle.test.ts.snap
- tests/components/lifecycle.test.ts
Before this commit, when willStart/willUpdateProps took more than 3s, a console.warn was done. In odoo, when a warning is logged during a test, the test fails and the build is considered as "in error".
There's a component that loads several resources (sequentially) in its onWillStart, which *sometimes* takes more than 3s, making builds fail non deterministically. Since a recent change (which adds another call in the problematic onWillStart), the warning gets logged quite often.
A quick fix is necessary, so we change the warn into a log, which won't make build fail.
We may consider alternatives in the future though:
- add a parameter to onWillStart, to disable the timeout, or to specify the delay (which is 3s by default)
- do not warn in test mode
> [FIX] runtime: log if willStart takes more than 3s

- tools/devtools/manifest-chrome.json
This commit ensures that the hook will properly be loaded on file urls when using chrome (this was already working in firefox). It is still necessary to check the "Allow access to file URLs" option in the extensions manager for this to work properly.
> [IMP] devtools: add support for file urls on chrome

- src/runtime/lifecycle_hooks.ts
Also unnest the handling of `result` via guard clauses, and generate messages as close as possible to use site, keeping the error construction itself where it currently is as the goal is specifically to point back to the *definition* site for the hook function.
> [IMP] make set of timeout-able hooks (and their timeouts)

- doc/reference/app.md
- src/runtime/app.ts
- tests/app/__snapshots__/sub_root.test.ts.snap
- tests/app/sub_root.test.ts
- tests/components/__snapshots__/basics.test.ts.snap
- tests/components/__snapshots__/props_validation.test.ts.snap
In this commit, we extend the owl App class to support multiple sub roots. This is useful for situations where we want to mount sub components in non-managed DOM. This is exactly what the Knowledge app is doing, with mounting views in an html editor.
Currently, this requires some difficult and fragile hacks, and still, the result is that it is very easy to mix components from the main App and a SubApp.  But Knowledge does not actually care about creating a sub app. It only needs the possibility to mount sub components in dynamic places.
closes #1640
> [IMP] owl: add basic support for sub roots

- .github/workflows/deploy.yml
- package.json
- tests/compiler/validation.test.ts
- tests/components/error_handling.test.ts
This commit bump the support for Node 20+.
> [IMP] Bump support for Node 20+

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
First commit makes it possible to expand empty classes to see their prototype instead of displaying them as simple empty objects.
Second commit ensures that class names are displayed for non generic objects and extensions of generic classes will have custom display for their content.
> [IMP] devtools: allow expansion of empty class and better class display

- doc/reference/app.md
- doc/reference/templates.md
- src/common/types.ts
- src/compiler/code_generator.ts
- src/compiler/index.ts
- src/compiler/inline_expressions.ts
- src/compiler/parser.ts
- src/index.ts
- src/runtime/template_set.ts
- tests/app/__snapshots__/app.test.ts.snap
- tests/app/app.test.ts
- tests/compiler/__snapshots__/t_custom.test.ts.snap
- tests/compiler/t_custom.test.ts
This commit adds the support for user-space directives. To use the user-space directive, an Object of functions needs to be configured on the owl APP:
```js
new App(..., {
userDirectives: {
my-user-directive: function (el, value) {
el.setAttribute("t-on-click", value);
return el;
}
}
});
```
The functions will be called when a user directive with the name of the function is found. The original element will be replaced with the one returned by the function.
This :
```xml
<div t-user-my-user-directive="click" />
```
will be replace by :
```xml
<div t-on-click="value"/>
```
issue : https://github.com/odoo/owl/issues/1650
> [IMP] parser: add support for user-space directives

- src/common/types.ts
- src/compiler/parser.ts
- tests/compiler/__snapshots__/t_custom.test.ts.snap
- tests/compiler/t_custom.test.ts
Since [1] it's possible to have a custom directive, this directive only supported one modifier. This commit, add the support to have multiple modifiers on a t-custom directive.
[1] : https://github.com/odoo/owl/commit/7e687234bf40bdcf5e6598401d8604d66b14ad32
> [FIX] compiler: multiple modifiers on t-custom

- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit solves issues with the observe variables functionality: it first restricts refreshing the observed variables to when owl is loaded on the page and then fixes how simplified paths are handled to find components so that both type of path will work fine no matter from where the function is called. This would cause issues when observing variables from the observed state section.
> [FIX] devtools: fix observe variables

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit makes the alphabetical sort of object keys account for numerical order as well so that it will feel right when handling objects with numerical keys.
> [FIX] devtools: sort object keys numerically as well

- doc/reference/templates.md
- doc/reference/translations.md
- src/compiler/code_generator.ts
- src/compiler/parser.ts
- src/runtime/template_set.ts
- tests/compiler/__snapshots__/translation.test.ts.snap
- tests/compiler/parser.test.ts
- tests/compiler/translation.test.ts
A new directive t-tanslation-context and a new family of directives (of the form
t-translation-context-...) are introduced to allow to translate terms in contexts.
Set t-translation-context="fr" on a node makes every call of the translation
function to be done with "fr" as seconde parameter when translating an
attribute/content within that node or its children (if no closer
t-translation-context directive is found).
A directive t-translation-context-attr="fr" can be used on a node to target its
attribute "attr". For example, if a div has an attribute title="a title",
use t-translation-context-title="pt" will make "a title" to be translated
in the context "pt". Note that this takes precedence over any other directive
t-translation-context found on a parent (or the div itself).
The …
> [IMP] translation contexts

- src/runtime/app.ts
- tests/components/props_validation.test.ts
- tests/misc/portal.test.ts
The owl dev info message may be useful, but does not bring that much value. Also, this is even slightly annoying while debugging odoo, since it is common to have to go to dev mode, and the message takes some visual space, which is a distraction.  In this commit, we simplify it to just warn that owl is in dev mode.
> [IMP] runtime: simplify info message when running in dev mode

- src/compiler/code_generator.ts
- tests/compiler/__snapshots__/t_slot.test.ts.snap
- tests/compiler/t_slot.test.ts
This commit removes an AST change during the code generation of slots. Before, the `compileTSlot` function deleted the `t-props` attribute directly on `ast.attrs`. This creates wrong code when compiling a second time as the `t-props` attribute does not exist anymore.
> [FIX] code generator: prevent AST change

- doc/reference/templates.md
- src/runtime/utils.ts
- tests/utils.test.ts
Allows markup to be called as a tag function. The interpolated strings are then safely escaped for injection in HTML code.
Example usage:
```js
const maliciousInput = "<script>alert('💥💥')</script>";
const value = markup`<b>${maliciousInput}</b>`;
// no problem, maliciousInput is properly escaped
```
> [IMP] runtime: add markup tag function

- src/runtime/utils.ts
- tests/shadow_dom/__snapshots__/shadow_dom.test.ts.snap
- tests/shadow_dom/shadow_dom.test.ts
Previously, `validateTarget` only checked if the target element or its host (if it was a ShadowRoot) was directly contained in the document body. This failed in cases where the target element was nested inside a shadow DOM, which itself was attached to the document.
This commit introduces a new helper `isAttachedToDocument` that traverses through parent nodes and shadow roots to ensure that the target is ultimately attached to the given document. Additionally, it now throws a clear error if `document.defaultView` is missing, indicating that the target document is detached or invalid.
This ensures proper validation of mount targets, including complex scenarios with shadow roots and iframes.
Before this commit, this threw an OwlError
```js
const shadow = fixture.attachShadow({ mode: "open" …
```
> [FIX] utils: Correct validation of mount target in shadow DOM/iframe

- src/runtime/index.ts
- src/runtime/utils.ts
- tests/utils.test.ts
markup tag function requires markup awareness to determine whether a given parameter should be escaped or not.
This implies that pre-escaped content should be properly marked'ed up to avoid double escaping. Having to manually wrap all calls to escape with markup is cumbersome and prone to issues (on top of having to be validated by the security team for no reason).
This commit introduces a markup-aware escape function to resolve those issues.
> [IMP] runtime/utils: export htmlEscape and add tests

- src/compiler/code_generator.ts
ARIA attributes containing human-readable text should be translated. This commit adds human-readable ARIA attributes to the list of the attributes translated by OWL.
> [IMP] compiler: make human-readable ARIA attributes translatable

- src/compiler/parser.ts
- tests/compiler/parser.test.ts
The directives t-esc/t-out both discard the ASTs that are not of DomNode type. Since the directives t-translation and t-translation-context both creates AST wrappers of type TTranslation and TTranslationContext respectively, mix t-esc/t-out and t-translation/t-translation-context does not work. For example parse
```xml
<span t-esc="'Hello'" t-translation="off"/>
```
gives the AST
```js
{
type: ASTType.TEsc,
expr: "'Hello'",
defaultValue: "",
}
```
This makes the span not been rendered in the end.
We fix that problem.
> [FIX] parser: t-esc/t-out vs t-translation*
