- tools/playground/app.js
> [IMP] playground: save changes to local storage

- src/qweb/extensions.ts
- tests/Context.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: event modifier with arg in t-foreach

- doc/qweb.md
- src/qweb/base_directives.ts
- src/qweb/extensions.ts
- src/qweb/qweb.ts
- src/vdom/html_to_vdom.ts
- tests/Context.test.ts
- tests/component/component.test.ts
- tests/hooks.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/vdom.test.ts
> [FIX] qweb: properly handle t-raw in various situations

- doc/component.md
- doc/hooks.md
- src/Context.ts
- src/component/component.ts
- src/hooks.ts
- tools/playground/app.js
> [IMP] component: add current key for easier hook creation

- doc/animations.md
- doc/component.md
- doc/observer.md
- doc/quick_start.md
- doc/store.md
- doc/tags.md
- doc/utils.md
closes #334
closes #336
closes #338
closes #339
> [DOC] update the documentation

- doc/quick_start.md
- doc/readme.md
- doc/utils.md
- src/qweb/extensions.ts
- src/utils.ts
- tests/qweb/qweb.test.ts
- tools/benchmarks/owl-master/app.js
- tools/playground/app.js
> [REF] utils: rename loadTemplates into loadFile

- doc/hooks.md
- doc/qweb.md
> [DOC] improve hooks and qweb doc

- doc/component.md
- doc/context.md
- doc/hooks.md
- doc/observer.md
- doc/readme.md
- doc/store.md
- doc/utils.md
closes #340
closes #344
closes #352
closes #355
> [DOC] improve the documentation

- doc/comparison.md
> [DOC] improve the comparison documentation page

- src/component/directive.ts
- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/animations.test.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
> [FIX] component: fix issues with component internal template key

- src/component/directive.ts
- src/qweb/base_directives.ts
- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: properly calls directive finalizers

- doc/store.md
> [DOC] improve store documentation on useGetters

- doc/qweb.md
> [DOC] qweb: document t-att variant

- src/qweb/base_directives.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: do not format expression twice in t-if

- doc/component.md
- doc/tags.md
- doc/tooling.md
- src/qweb/extensions.ts
- tests/component/component.test.ts
- tests/qweb/qweb.test.ts
> [DOC] add more info on xml tag and single file component

- tools/playground/app.js
> [IMP] playground: log url for current owl commit

- doc/component.md
- doc/context.md
- doc/quick_start.md
- doc/qweb.md
- doc/utils.md
- src/context.ts
- src/index.ts
- src/qweb/qweb.ts
- tests/context.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tools/benchmarks/owl-master/app.js
- tools/playground/app.js
- tools/playground/samples.js
> [IMP] qweb: add an option to setup a translate function

- doc/hooks.md
- doc/store.md
> [DOC] store,hooks: useState/useStore should return object

- src/router/router.ts
- tests/router/router.test.ts
> [FIX] router: preserve pathname in hash mode

- src/component/component.ts
- src/component/directive.ts
- src/component/fiber.ts
- src/component/props_validation.ts
- src/component/scheduler.ts
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/component/props_validation.test.ts
- some error handling improvements
- close an issue with props validation
> Master error handling

- src/core/observer.ts
- src/store.ts
- tests/core/observer.test.ts
> [REF] observer: remove revNumber

- src/component/component.ts
- src/component/fiber.ts
- src/component/scheduler.ts
- src/context.ts
- tests/component/component.test.ts
- tests/helpers.ts
> [FIX] component: error handling: rendering with sub components

- src/component/component.ts
> [IMP] component: expose scheduler instance

- src/component/component.ts
- src/component/directive.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
Resolved rendering with cancelled fiber for (not yet) destroyed
component -> Cannot read property 'sel' of null
Closes #421
> [FIX] component: concurrent rendering issue

- src/component/props_validation.ts
- tests/component/props_validation.test.ts
> [FIX] component: fix invalid prop validation situations

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- src/qweb/expression_parser.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: allow mixing body and expression variables

- src/component/component.ts
- src/qweb/base_directives.ts
- tests/component/component.test.ts
> [IMP] component: display better error message if render is empty

- src/component/directive.ts
- src/context.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/context.test.ts
- tests/router/__snapshots__/route_component.test.ts.snap
> Components destroyed before being mounted

- doc/reference/component.md
- src/component/component.ts
- src/core/owl_event.ts
> [IMP] component: introduce OwlEvent

- doc/reference/component.md
- src/component/component.ts
- tests/component/component.test.ts
It is now possible to mount components in fragments
closes #494
> [FIX] component: allow fragments in method mount

- doc/reference/component.md
- src/component/props_validation.ts
- tests/component/props_validation.test.ts
> [IMP] component: allow custom validator functions for props

- doc/reference/store.md
- src/store.ts
- tests/store_hooks.test.ts
> [IMP] store: allow useStore to return primitive types

- package.json
- src/vdom/vdom.ts
- tests/component/component.test.ts
- tests/qweb/qweb.test.ts
- tests/qweb/qweb_expressions.test.ts
- tests/router/link.test.ts
- tests/store_hooks.test.ts
also, run prettier on codebase
closes #498
> [FIX] owl: add prettier to devDependencies

- doc/reference/store.md
- src/store.ts
- src/vdom/vdom.ts
- tests/component/component.test.ts
- tests/qweb/qweb.test.ts
- tests/qweb/qweb_expressions.test.ts
- tests/router/link.test.ts
- tests/store_hooks.test.ts
> [IMP] store: prevent changes to store state in useStore return value

- src/qweb/compilation_context.ts
- src/qweb/extensions.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
> [FIX] qweb: scope t-key directive to node and subnodes

- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/router/__snapshots__/link.test.ts.snap
> [FIX] t-slot: correct parented relationship with nested slots

- tools/playground/samples.js
as Edge doesn't support them.
Closes #509
> [FIX] playground: stop using class fields

- src/component/component.ts
- src/component/fiber.ts
- tests/component/component.test.ts
> [FIX] slots: use correct scope and vars at update

- doc/learning/testing_components.md
- doc/readme.md
- doc/tooling.md
- tests/component/component.test.ts
- tests/doc_link_checker.test.ts
- tools/debug.js
> [IMP] tooling: add debug code

- src/component/component.ts
- src/component/directive.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/animations.test.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/component.test.ts
- tests/router/__snapshots__/link.test.ts.snap
- tests/router/__snapshots__/route_component.test.ts.snap
> [FIX] component: tricky concurrency issue

- doc/reference/qweb_templating_language.md
- src/misc/portal.ts
- src/qweb/qweb.ts
- tests/misc/portal.test.ts
> [DOC] add some information on variables and t-call

- src/qweb/expression_parser.ts
- tests/qweb/qweb_expressions.test.ts
> [IMP] qweb: add support for arrow functions in expression parser

- doc/reference/component.md
- src/qweb/extensions.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
> [IMP] components: slots can now define default content

- src/component/directive.ts
- src/qweb/compilation_context.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/animations.test.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/props_validation.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/router/__snapshots__/link.test.ts.snap
- tests/router/__snapshots__/route_component.test.ts.snap
In some cases, we can simply inline a template key instead of assigning
it to a variable and then using that variable
> [IMP] qweb: slightly simplify generated templates

- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: t-set with a body should not be joined with comma

- src/store.ts
- tests/store_hooks.test.ts
> [FIX] store: make Array.map work correctly on the result of selector

- src/qweb/expression_parser.ts
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
- tests/qweb/qweb_expressions.test.ts
> [FIX] qweb: add support for spread operator

- doc/readme.md
- doc/reference/component.md
- doc/reference/tags.md
- doc/tooling.md
- src/component/component.ts
- src/component/styles.ts
- src/tags.ts
- tests/component/component.test.ts
- tests/component/slots.test.ts
- tests/component/styles.test.ts
> [IMP] component/tags: add inline css tag

- src/qweb/expression_parser.ts
- tests/qweb/qweb_expressions.test.ts
> [FIX] qweb: add support for "in " operator in expressions

- src/qweb/base_directives.ts
- src/qweb/compilation_context.ts
- src/qweb/expression_parser.ts
- src/qweb/extensions.ts
- src/qweb/qweb.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/__snapshots__/slots.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
This PR puts together the main principles of #599 and #597.
The two issues are treated differently, in two separate commits.
But their reunion in one PR allows for consistency
> [FIX] qweb: code block scoping  (foreach)

- doc/reference/component.md
- doc/reference/concurrency_model.md
- doc/reference/environment.md
- tools/playground/samples.js
While studying how to use owl, I noticed some issues and I'm making this pull request as proposed solution.
> Master owl simple corrections jcb

- doc/reference/hooks.md
- src/hooks.ts
- src/qweb/compilation_context.ts
- src/qweb/expression_parser.ts
- tests/component/component.test.ts
- tests/component/styles.test.ts
- tests/hooks.test.ts
- tests/tooling/debug_script_4.test.ts
It is very useful.
Also, this commit prettifies the code.
closes #608
> [ADD] hooks: add useExternalListener hook

- doc/reference/store.md
> [DOC] store: clarify how a component can find a store

- src/hooks.ts
so it can work on window
closes #613
> [FIX] types: improve type of useExternalListener

- doc/miscellaneous/why_owl.md
> [FIX] typo

- src/component/component.ts
- src/component/directive.ts
- src/component/fiber.ts
- src/component/scheduler.ts
- src/misc/portal.ts
- tests/__snapshots__/animations.test.ts.snap
- tests/component/component.test.ts
- tests/component/un_mounting.test.ts
> [FIX] component: cancel previous mounting operations if necessary

- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [FIX] qweb: support attributes with quotes

- doc/reference/event_handling.md
- src/component/directive.ts
- src/qweb/extensions.ts
- src/vdom/modules.ts
- tests/component/__snapshots__/component.test.ts.snap
- tests/component/component.test.ts
- tests/qweb/__snapshots__/qweb.test.ts.snap
- tests/qweb/qweb.test.ts
> [IMP] qweb: add support for event capture

- package.json
> [MISC] set package.json license field to a valid SPDX expression

- src/component/component.ts
- tests/component/component.test.ts
- tests/component/un_mounting.test.ts
> [FIX] component: properly handle mounting a destroyed component

- README.md
- tools/release.js
@ged-odoo you'll need to install https://cli.github.com/. 
The first time you will use it, it will ask you to launch the command gh login to connect to your github action.
Maybe do it first to avoid problems. 
I'd like a rollback feature if the last steps of the deployment fail. Because we have the problem of a new commit and a push being done. But because of the push, we would need a --force so it's not great.
> Improve the release script for easier deployment

- .github/workflows/deploy.yml
Add the npm run prettier command action to every push request
> Update deploy.yml => add prettier

- rollup.config.js
> [IMP] rollup: properly indent generated files

- doc/learning/overview.md
Proposed by @obayit with https://github.com/odoo/owl/pull/689
> [DOC] minor fix - missing `this`.

- doc/miscellaneous/why_owl.md
Correct minor grammatical mistakes in the `why_owl.md` file
> Improve documentation

- doc/reference/content.md
- doc/reference/hooks.md
- src/hooks.ts
- tests/hooks.test.ts
This commit introduces three new hooks: useComponent, useProps and
useEnv.
> [IMP] hooks: add some building blocks for hooks

- doc/learning/tutorial_todoapp.md
APP gets error while running "ReferenceError: mount is not defined"
because of mount not defined with "Component"
> [FIX] todoapp mount issue

- src/store.ts
- tests/store_hooks.test.ts
Before this commit, the following scenario could happen:
Suppose that we have a parent component A, connected to a store,
and a child component B, also connected to the store and using
the onUpdate feature.
Then, we remount the A component in some other places and a
rendering is initiated in A.  We immediately update the store state.
What happens next is:
- rendering A is done, A internal revid is updated
- store update A (but nothing is done because the state change here
does not modify A)
- rendering B is done (from parent), B internal revid is updated
- store update B, notice internal revid is updated, does not call the
onUpdate function
We then have the B component which has not its internal state updated,
because we did not call its onUpdate function.
The solution is to move the …
> [FIX] store: properly call onUpdate functions in some cases

- doc/learning/tutorial_todoapp.md
- doc/reference/component.md
- doc/reference/observer.md
- doc/reference/slots.md
> [DOC] misc small fixes

- package.json
- tools/release.js
> [IMP] Tooling: release script errase dist folder

- package.json
- tools/release.js
Release script errase dist folder
closes #793
Release can only be done on master branch
closes #829
Update the playground owl version on release
closes #814
Add logError method in release to show messages in red.
Check-formatting command added to the release process.
> Improve tooling ges

- doc/reference/qweb_templating_language.md
- src/qweb/qweb.ts
- tests/qweb/__snapshots__/qweb_t_tag.test.ts.snap
- tests/qweb/qweb_t_tag.test.ts
Very useful in some cases, when one needs to define a generic component.
closes #721
> [IMP] qweb: add support for t-tag directive

- src/component/fiber.ts
- tests/component/error_handling.test.ts
Before this commit, the error handling process was too naive: once an
error occurs in a rendering, owl catch it, looks for a component that
implements the catchError method, then calls it.
However, in real life, we sometimes need to rethrow that error (or
another one) to propagate the error to some parent handler. This error
needs to be handled by the closest parent component that implements
catchError.
This is what this commit implements: it wraps the catchError call in a
try/catch, then in case of errors, try to handle it by a parent.
> [FIX] component: propagate errors to parent

- src/qweb/compiler.ts
- src/qweb/parser.ts
- tests/components/__snapshots__/t_props.test.ts.snap
- tests/components/basics.test.ts
- tests/components/concurrency.test.ts
- tests/components/t_props.test.ts
- tests/qweb/parser.test.ts
We reimplement the directive t-props and some tests for it.
> [IMP] qweb: t-props directive

- tests/qweb/__snapshots__/attributes.test.ts.snap
- tests/qweb/attributes.test.ts
- textarea with t-att-value
- select with t-att-value
> [IMP] qweb/attributes: uncomment two tests

- src/app/app.ts
It should be usefull to allow developpers to implement mounting/unmounting
if they wish to.
> [FIX] app: factorize to allow smoother developments in projects

- src/hooks.ts
- tests/components/__snapshots__/hooks.test.ts.snap
- tests/components/hooks.test.ts
Because the dependencies are now computed in patched.
> [FIX] useEffect: can depend on dom dependencies

- src/app/template_helpers.ts
- src/blockdom/block_compiler.ts
- src/blockdom/list.ts
- src/blockdom/multi.ts
- src/compiler/code_generator.ts
- src/compiler/parser.ts
- src/index.ts
- src/portal.ts
- tests/compiler/parser.test.ts
- tests/misc/__snapshots__/portal.test.ts.snap
- tests/misc/portal.test.ts
This commit also clean-up the deepRemove for the Portal that is not
needed any more.
> [IMP] portal: compile t-portal in an internal Component Portal

- doc/reference/app.md
- src/app/app.ts
Same as `dev` mode, but without warning in console
> [IMP] app: introduce `test` mode

- src/compiler/inline_expressions.ts
- src/component/lifecycle_hooks.ts
- tests/compiler/inline_expressions.test.ts
- tests/components/__snapshots__/error_handling.test.ts.snap
- tests/components/error_handling.test.ts
> [IMP/FIX] compiler, components: improve error messages and fix error wrapping

- doc/reference/app.md
- src/component/component_node.ts
also, improves the implementation of subscriptions
> [IMP] component: add name property on nodes for debug purposes

- src/runtime/blockdom/event_catcher.ts
- tests/components/__snapshots__/t_on.test.ts.snap
- tests/components/t_on.test.ts
> [FIX] component: fix wrong behaviour when using t-on on t-component

- tests/compiler/__snapshots__/misc.test.ts.snap
> [FIX] tests: update wrong snapshot

- doc/learning/tutorial_todoapp.md
There are two deleteTask functions in step 9. This will make sure the developer/student
does not miss one of those.
> [IMP] Add a notice to step 9

- tools/release.js
This template contains the release version as a markdown title followed by a markdown list with all the commit titles since the previous release.
> [IMP] tools: release scripts creates a template for release notes

- src/runtime/reactivity.ts
Previously, when having a long lived reactive object and writing a lot of keys to it, clearing the reactive subscriptions on that object would slow down as time went on. This is because when clearing a target's subsctiptions for a callback, we look at all the keys that are observed, and for all the observed keys, we remove the callback from the set of callbacks observing that key. The problem arises from the fact that after doing that, even if the set of callbacks observing that key is now empty, we don't remove the key from the observed keys, meaning that any further clearing of subscriptions will have to iterate over that key to attempt to clear the callbacks even if there are none.
This commit fixes this problem by simply removing the key from the observedKeys if there are no longer …
> [FIX] reactivity: improve performance for long-lived reactives

- src/runtime/app.ts
Useful for tooling purpose
closes #1342
> [IMP] app: add name as a config option

- tools/devtools/src/utils.js
This commit fixes the issues that were happening when using the devtools in a detached window
> [FIX] devtools: Fix devtools in detached window

- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
This commit fixes some race conditions that were happening due to the loading of the tree being sometimes triggered at the same moment as the DOM patch. This would result in some destroyed component still being present in the devtools' tree. This commit also ensures that the loading of the tree is synchronous in regard to the component details loading.
> [FIX] devtools: Fix race conditions in tree lodaing

- tools/devtools/src/page_scripts/owl_devtools_global_hook.js
Since we now omit some observed objects when listing subscriptions, the index of the subscription is no longer the index of the raw subscription. This causes issue with the resolution of object paths when they are inside a subscription. This commit fixes that by adding the index to the raw subscription.
We also need to adapt the code that traverses the old tree, since the index of the subscription in the component is no longer the same as the index of the subscription "child" in the object tree.
> [FIX] devtools: fix incorrect path resolution for subscriptions

- src/runtime/utils.ts
Currently the implementation of batched is quite complicated and difficult to read. This is because this approach tried to block all calls at the same point and then only let the first one go through, but an alternative approach is to simply throw away the calls that are made after the first one has been scheduled. This change makes the implementation much simpler to understand.
> [REF] runtime: simplify implementation of batched

- docs/playground/samples/todo_app/todo_app.js
Just fixed a little bug when click on "Clear Completed"
Also removed unusefull method.
> [FIX] playground: todo app clear complete tasks

- tools/devtools/src/devtools_app/store/store.js
This commit makes the component search more interactive by highlighting the component search results on the page when navigating through them.
> [IMP] devtools: highlight searched components

- tools/devtools/src/devtools_app/store/store.js
This commit ensures that search results are properly updated when the components tree is updated so that it remains coherent if search results appear or disappear from the view.
> [FIX] devtools: update search results on tree change

- tools/devtools/src/devtools_app/devtools_window/components_tab/component_search_bar/component_search_bar.xml
- tools/devtools/src/devtools_app/devtools_window/components_tab/details_window/object_tree_element/object_tree_element.xml
- tools/devtools/src/devtools_app/devtools_window/devtools_window.xml
- tools/devtools/src/devtools_app/devtools_window/profiler_tab/profiler_tab.xml
- tools/devtools/src/devtools_app/store/store.js
- tools/devtools/src/main.css
This commit adapts the layout of icons in the UI to be more intuitive and also adds some feedback on hover on some elements for clarity. Also fixes a bug where an object line could be toggled on select.
> [IMP] devtools: icons and UI improvements

- tools/devtools/src/devtools_app/store/store.js
Small imp to highlight a component when it gets selected in the tree to provide better visual feedback to the user when he is using arrow keys navigation.
> [IMP] devtools: highlight component on select

- doc/reference/hooks.md
> [IMP] doc: improve documentation of useExternalListener

- doc/reference/props.md
Fixed brackets on props validation example
> [FIX] Typo docs

- doc/readme.md
- doc/reference/utils.md
- src/runtime/index.ts
'batched' will be used in odoo/o-spreadsheet.
There's also a copied version (slightly modified) in odoo/odoo.
It shows it could be useful outside owl.
> [IMP] index: export batched utility function
